### ISSUE TITLE
Trails QuickStart Errors: #v1.0.0-beta-1

### ISSUE THREAD

**Issue by maissani** [trailsjs/trails#100]
### Environment details
> node v5.6.0
> npm v3.7.3

#### Dependencies in packages.json
```json
  "dependencies": {
    "jade": "^1.11.0",
    "lodash": "^3.10",
    "rc": "^1.1",
    "trailpack-core": "1.0.0-alpha-2",
    "trailpack-hapi": "^1.0.0-beta-2",
    "trailpack-repl": "1.0.0-alpha-3",
    "trailpack-router": "1.0.0-alpha-2",
    "trails": "latest",
    "trails-controller": "1.0.0-alpha-1",
    "trails-model": "1.0.0-alpha-1",
    "trails-policy": "^1.0.0",
    "trails-service": "1.0.0-alpha-1",
    "winston": "^2.1.1"
  },
````
### How to reproduce
Follow that getting started guide (clean trails install)
Options: Hapi
### What did happens
After the ```npm start```command: 
It seems that there is an error in trailpack-core at line 47
> obj[method].bind is not a function

That occurs after the event router initialized in the last version of trails. 
It's probably a lodash use error => Check Changes to each Function. 
### Question
Can someone please confirm that it's not only from my environment and set it as bug. 

Cordially, 
Mehdi AISSANI

**Comment by RothAndrew** [comment]
Can you post the dependencies section of your package.json? I had the same problem and it was fixed by updating dependency versions. I'll scrounge up what my dependencies section looked like when I got it to work

**Comment by RothAndrew** [comment]
...
"dependencies": {
    "jade": "^1.11.0",
    "lodash": "^3.10",
    "rc": "^1.1",
    "trailpack-core": "^1.0.0-beta-3",
    "trailpack-hapi": "^1.0.0-beta-2",
    "trailpack-repl": "1.0.0-alpha-3",
    "trailpack-router": "^1.0.0-beta-4",
    "trails": "latest",
    "trails-controller": "1.0.0-beta-2",
    "trails-model": "1.0.0-beta-2",
    "trails-policy": "^1.0.0",
    "trails-service": "1.0.0-beta-2",
    "winston": "^2.1.1"
  }
...

See issue #99 for more.

**Comment by maissani** [comment]
Yes, this seems to be a duplicate to #99. I have to close it and continue into the #99 issue.
