### ISSUE TITLE
Change environment mode

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#101]
I'm trying to change `development` environment to `production` (or anything else) and it's not working. The console tell me I'm under `development`.

I have tried this :

```
node server.js --prod
or
node server.js --production
or
NODE_ENV=production
node server.js
``` 

This is plan to work only for the first release or it's a bug ?

**Comment by tjwebb** [comment]
This should work:

```sh
$ NODE_ENV=production node server.js
```

Trails doesn't currently support any command-line flags, e.g. `--prod`

**Comment by jaumard** [comment]
You're right in one line it's working ! But it doesn't use `config/env/production.js` file. `trailpack-repl` is not disable, I can see debug logs and I put some config for `trailpack-gulp` to build assets in production mode but it take the dev tasks.

**Comment by jaumard** [comment]
Closing this on open another one about config env merge
