### ISSUE TITLE
[spec] .trails folder

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#103]
Create a spec that allows trailpacks to make use of the filesystem according to a convention. This would be similar to `.tmp/` in sails, but would be more formalized in the documentation and the API.

**Comment by Alaneor** [comment]
Is this intended only as temporary storage or as an API for a persistent data store? The latter would be rather interesting if it could be swappable, ie. one API for S3, GridFS, Azure Blob Storage etc.

**Comment by tjwebb** [comment]
Mainly as a default folder for temporary app storage. e.g., for a sqlite database, compiled assets, and so forth.

**Comment by tjwebb** [comment]
This should be defined by a trailpack, not the core. Closing.
