### ISSUE TITLE
getBaseUrl and getHost

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#104]
Can be useful to have `getBaseUrl` and `getHost` method into Trails like this Trailpack who need host or base url can access to it.

**Comment by Alaneor** [comment]
Would this be somehow detected or provided by user via configuration?

I am just thinking how to go about detecting your host in a way that works for all (or at least most) hosting providers (Heroku, AWS, etc.).

**Comment by tjwebb** [comment]
> how to go about detecting your host in a way that works for all (or at least most) hosting providers (Heroku, AWS, etc.)

yea, a general solution here is difficult. You could *declare* the host/baseurl in environment variables, but I don't think you could reliably *detect* them. If the web server is fronted by a load balancer or some other reverse proxy (which I typically recommend) then the host will be some internal ip address. It's also common to rewrite urls during proxying, so baseurl would be hard to generalize as well.

@jaumard can you be more specific about your intended use case?

**Comment by jaumard** [comment]
@tjwebb I need it for `trailpack-passport` to give the callback URL to third party providers here https://github.com/jaumard/trailpack-passport/blob/22556ee56d115039f6d3ccd63a9d1c3bec66f705/lib/passports.js#L157 

In my previous module `sails-hook-passport` I use the default `sails.getBaseUrl()` method here : https://github.com/jaumard/sails-hook-passport/blob/4f56b6777722675b8153e66615246428f9cea467/api/services/passport.js#L360

I suppose I can get `web.host` and `web.port` but maybe a global method to have only one access point will be better ? Cause for example to detect http/https it can be more tricky depends of the web server maybe

**Comment by randallmeeker** [comment]
should probably be an environmental variable that can be set per machine. So it can be read from configs like in heroku or in elastic beansstalk ect. . . that way you can push to machines on different providers

**Comment by Alaneor** [comment]
Original implementation can be found [here](https://github.com/balderdashy/sails/blob/master/lib/app/private/getHost.js).

It's all gathered from explicit configuration.

**Comment by jaumard** [comment]
Also implementation of getBaseUrl can be found here https://github.com/balderdashy/sails/blob/27fbc59c87a41eebd9e6a4ebf0a7d87c0d3ba5f1/lib/app/getBaseurl.js

**Comment by Alaneor** [comment]
What @randallmeeker said. I wonder if this information could be useful in other instances, right now nothing comes to my mind. If not, then perhaps the best solution would be to include the explicit host configuration in a `trailpack-passport` specific configuration option...

**Comment by jaumard** [comment]
@Alaneor it can be use for sending emails with links in it for example

**Comment by tjwebb** [comment]
@jaumard @Alaneor Sorry I didn't notice this earlier, but `getBaseUrl` is being deprecated in Sails: https://github.com/langateam/sails-auth/issues/126.

If you can describe the intended use cases in a separate issue, we can come up with a way to solve those problems.
