### ISSUE TITLE
listening to events on the global process object waters down the advantages of encapsulation

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#111]
Trails very intentionally does not pollute the global namespace with things like models, controllers, or some global `trails` object. This is a technical blunder that Sails made, which we aim to not repeat. 

However listening to things like "uncaughtException" on the global `process` object is an edge-case form of this pollution. For example, imagining an application which wanted to run and manage multiple trails instances in a single node process (which is possible), these listeners would become indistinguishable. When an exception occurred, it will be impossible to tell from which trails application it originated. What's not clear to me is 1) whether there is another way to handle uncaughtexceptions in a way that could tie them to a particular trails app instance, 2) whether it's worth it to complicate the code with the solution to a problem that may never exist.

**Comment by Alaneor** [comment]
If we want to achieve full encapsulation of Trails apps in a single process, then those listeners on `process` have to go away. Right now, if one Trails app crashes, all the Trails apps will just shut themselves down. This may or may not be desirable, though - a process which just experienced an uncaught exception might be in no good shape to continue operating. However, it's true that finding out **which** Trails app actually caused the issue might be hard with current approach.

Usually, [domains][https://nodejs.org/api/domain.html] come to mind when there is need to catch errors from event emitters, callbacks or timers in a way that prevents a crash. In our scenario, we do not have to prevent the crash from happening, but using the domain can help us detect which Trails app crashed.

There's a [great writeup on domains here](https://engineering.gosquared.com/error-handling-using-domains-node-js) if you are interested, it helped me a lot to understand how domains work. And you can see them used in action [here](https://github.com/nodestream/nodestream/blob/c54e9b08e3fb777ea42acd75ac4433e1ccd0a2e2/lib/nodestream.js#L93). I believe Sails also uses domains to handle request/response errors.

I have not looked at how hard it would be to add this to Trails, but I am assuming it would be pretty straightforward.
