### ISSUE TITLE
following starting video issues

### ISSUE THREAD

**Issue by jmcfet** [trailsjs/trails#117]
https://www.youtube.com/watch?v=AbSp8jqFDAY  is the video by Travis that I tried following but ran into this issue:

I got by the waterline sqllite issue and can start up a default app. I see the **user **model definition . Looks interesting at this point, I do a //localhost:3000 request and see Hello Trails.js !  The video implies that I can consume the user object with no more code but do not see how that is possible as there is no route for user or no default implementation like sails has with Blueprints. If I do a Get http://localhost:3000/api/v1/user I get a 404.

now travis suggested adding api/v1 to   config/footprints.jsit is already there
prefix: '/api/v1'

**Comment by jaumard** [comment]
This bug will be fix by : 
https://github.com/trailsjs/trailpack-footprints/pull/6
And
https://github.com/trailsjs/generator-trails/pull/31 (depend on https://github.com/trailsjs/trails/pull/131)

**Comment by jaumard** [comment]
Now it have to work correctly. Both fixes are under npm.

**Comment by jaumard** [comment]
@wbprice this can be close
