### ISSUE TITLE
implement and test trailpack-swagger

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#12]

**Comment by konstantinzolotarev** [comment]
I'm working on adding swagger to my hapi project and could work on this for trails.

**Comment by tjwebb** [comment]
Awesome! Yea probably using https://github.com/tjwebb/sails-swagger as a guide might help as well

**Comment by grocky** [comment]
Hi @konstantinzolotarev! Have you made any progress on this? I'd like to help get this implemented.

**Comment by tjwebb** [comment]
https://github.com/trailsjs/trailpack-swagger
