### ISSUE TITLE
implement trailpack generator

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#13]
The current trails generator works for creating new trails apps (https://github.com/trailsjs/generator-trails). We need to build an analog for trailpacks that generates the stuff in trailpack/archetype. Usage will be similar to the trails generator.

**Comment by YannBertrand** [comment]
@jaumard and I are [working on it](https://github.com/jaumard/generator-trailpack). We'll do a PR asap ;)

**Comment by jaumard** [comment]
https://github.com/trailsjs/generator-trailpack is here, same usage as `generator-trails` :) 
- generates the stuff in trailpack/archetype
- generate api/model/controller/service/policy
