### ISSUE TITLE
Help needed: File upload examples for various size of file

### ISSUE THREAD

**Issue by Nishchit14** [trailsjs/trails#130]
File uploading seems crucial part in many nodeJS frameworks. I have personally felt many difficulties with multer and skipper with sails.

People should have good command on handling file uploads so they can get surety and can move on nice framework with confidence.

Here i am suggesting some variations for file upload, i think it will help new comers.
1) Local file storage 100kb to 50mb with multipart.
2) Local file storage for big file like 100mb to 1gb multipart.
2) Bulk file upload with multiple option in file input (10mb to 100mb)
3) Bulk file upload with multiple file input with single selection option (10mb to 100mb)
4) AWS cloud store example for small and big file.

There are many more variations too, but these are enough to achieve trust.

**Comment by Alaneor** [comment]
There's [Nodestream](https://github.com/nodestream/nodestream) *(disclaimer: I am the developer of that library).* The aim is to support file uploads/downloads to any file storage system. Currently these are supported:

- AWS S3
- Local disk
- Google Cloud Storage

You can use it as-is to upload files to which you already have access (ie. files you yourself generate or which you already have on your local filesystem). For HTTP file uploads, one would need to parse the incoming http file upload body and obtain a readable stream of that data/save the data to a temporary file on disk. Then it's quite straightforward - just give the stream to Nodestream and let it do the rest.

**Comment by jaumard** [comment]
@Alaneor your module look good ! It can be nice to have a module base on it to have express4 mutlipart support

**Comment by Alaneor** [comment]
Yup, writing something that integrates Express/Hapi and Nodestream in a usable manner (somewhat like Skipper does - just `req.file()` it and you get the stream) was a TODO for me, but I am still working on adding more adapters and transforms so that it's as much usable as possible.

Once that's done, writing a trailpack should be trivial.

**Comment by jaumard** [comment]
@Alaneor would be cool if we can make something who work with hapi and express, this 2 web server work differently :/ as I can think of it will be complicated to make a trailpack.
For express skipper is only a middleware load by `app.use` where hapi use plugins.
But if I can help with this let me know ;)

**Comment by Alaneor** [comment]
I still have some work to do on the core concepts and the surrounding plugins, so not planning on working on integration with frameworks anytime soon. If you feel like, have a go at it, that would be awesome! If you ever need some guidance, feel free to open an issue in the main repo, I'll be happy to help.

**Comment by Nishchit14** [comment]
:+1: 
@Alaneor Nice job ... I will take a look 

@jaumard  right now is there any solution ?  skipper works with trails ?

**Comment by jaumard** [comment]
You can use any module you want but there nothing official for trails.
For example for express I use multer. Skipper have to work too but only with express

**Comment by tjwebb** [comment]
Skipper is reliant on express3. Skipper is actually a fairly decent idea in theory, but its codebase is a sprawling mess with tons of issues. It's about 10x more complex than it needs to be. Moreover, it's essentially a glorified hack: it polls its own request at an interval until something that looks like a file appears. Then it tries to parse it and feed it into a steam. This is inefficient and has a lot of disadvantages. It also has known issues working properly with SSL.

For app-specific cases like file uploading, I think Trails may offer some recommendations and tutorials on using various file upload tools with Trails (whether with hapi, express, *et al*) but I don't think we will take a stance on choosing some particular API for file uploading and integrating it. There are a lot of different ways to do file uploads, and we'd prefer to let users choose.

**Comment by jaumard** [comment]
Closing this as Trails will not provide something custom here. 
BTW @Alaneor how your nodestream module goes ? any trailpack on the way ? ^^
