### ISSUE TITLE
docs should recommend against using "npm start" for production use

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#132]
see https://medium.com/@tjwebb/the-npm-start-default-uses-a-lot-of-ram-3e0d8ac0c6a1#.aqqu03syn

**Comment by Alaneor** [comment]
Oh, definitely!

**Comment by jaumard** [comment]
Sure ! I don't use npm start ^^ but didn't know about this :) thanks!

**Comment by jaumard** [comment]
FYI @maissani

**Comment by maissani** [comment]
Oh, i ll add this. 
Thanks a lot

**Comment by maissani** [comment]
It has been Fixed, checks the docs.

Best regards
