### ISSUE TITLE
get rid of trailsrc

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#139]
## Issue Description
trailsrc is redundant. solve this by using a `env/local.js` config file only.

**Comment by tjwebb** [comment]
@jaumard this used to be here, but I can't find it in trails or generator-trails. Did we already remove it?

**Comment by jaumard** [comment]
> “Your eyes can deceive you. Don’t trust them.” – Obi-Wan Kenobi
lol I just remove it from generator-trails but it's on a pending PR.
For trails it's just here https://github.com/trailsjs/trails/blob/master/archetype/.trailsrc

**Comment by jaumard** [comment]
I think this can be close now @tjwebb
