### ISSUE TITLE
trailpack icons

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#15]
Need icons for the following things:
- trailpack
- hapi trailpack
- router trailpack
- repl trailpack
- core trailpack

I wonder if we can continue the node.js hexagon theme and show a trail running through them when they're connected up? If this idea is terrible let me know.

**Comment by jaumard** [comment]
Maybe an icon by "family" will be nice ? Like : 
- hapi trailpack, express trailpack... for web server
- Webpack, grunt, gulp... for resource builder 
...

Like this icons are nice and they also a purpose :) the user can easily they are for the same goal. 
Just an idea ^^

**Comment by yejodido** [comment]
@tjwebb I'll pass the ideas by Jon today.

@jaumard I think there's definitively a theming component to what you're saying that I think would be great. To be able to easily identify the type of trailpack at first glance, but have it dynamically change based on the user's preference.

**Comment by jaumard** [comment]
@yejodido yes that's why I mean :) thanks

**Comment by tjwebb** [comment]
@yejodido is Jon on github? If not, get him in here :)

**Comment by yejodido** [comment]
@jonhargreaves ^

**Comment by jonhargreaves** [comment]
@yejodido I will gladly get started on some icon designs. :)

**Comment by tjwebb** [comment]
@jonhargreaves @yejodido bump
