### ISSUE TITLE
Generators should all run CI on Windows and OSX

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#169]
#### Issue Description

The following should set up AppVeyor

- [ ] generator-node
- [ ] generator-trails
- [ ] generator-trailpack

**Comment by tjwebb** [comment]
Setup via ecosystem ci tests: https://github.com/trailsjs/smokesignals/blob/master/lib/ecosystem.js#L10-L12

**Comment by jaumard** [comment]
Eco ci doesn't work on windows as I understand. Maybe it's a good idea to set it manually like trails on appveyor ? At least generator-trails and generator-trailpack to be sure they work everywhere

**Comment by tjwebb** [comment]
Yea, re-opened. The issue is actually with `npm`. It won't work until this is merged: https://github.com/npm/npm/pull/12333

**Comment by jaumard** [comment]
Done :) this can be close @tjwebb @wbprice
