### ISSUE TITLE
TypeError: Cannot prevent extension of an object with external array elements

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#177]
#### Issue Description
Object.freeze on some arrays causes exception to be thrown:

```
TypeError: Cannot prevent extension of an object with external array elements
```

Looks like possibly a v8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=4460

#### Environment
- node version: 4.4.4
- trails version: master
- operating system: all?

**Comment by tjwebb** [comment]
@jaumard your express trailpack helped me discover this issue, actually :)  Because `express` isn't in the application's package.json, the application isn't aware of express as an external dependency, and tries to freeze it. When it tries to freeze it, this occurs: https://travis-ci.org/trailsjs/trails/jobs/128392383#L1160

I'm making the config freeze more robust and more aware of these dependencies. The freeze of the config will be important so that all trailpacks can depend on the fact that the config will not be modified during the `initialize()` phase by any other trailpack.

**Comment by jaumard** [comment]
Another error (crash) I just discovered, I'm working on an example project with Trails and Angular 2 but the freeze capabilities prevent my code to work because angular2 can't be `require` so I have this error : 
```
error: 
 Error: Cannot find module 'angular2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:119:53
    at Array.find (native)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:119:36
    at Array.forEach (native)
    at Object.freezeConfig (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:117:15)
    at TrailsApp.<anonymous> (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trails.js:169:59)
    at TrailsApp.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TrailsApp.emit (events.js:166:7)
    at TrailsApp.emit (/Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/index.js:142:23)
    at /Users/jaumard/IdeaProjects/trails-example-express-gulp-angular2/node_modules/trails/lib/trailpack.js:34:23
    at process._tickDomainCallback (node.js:407:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3
error: The application did not boot successfully.
```

The error come from here https://github.com/trailsjs/trails/blob/master/lib/trails.js#L119 when it try to do `require('angular2')`

**Comment by jaumard** [comment]
Any way to force Trails to not freeze configuration ? maybe it can be useful during development... or like in this situation ^^

**Comment by tjwebb** [comment]
> prevent my code to work because angular2 can't be require so I have this error

You should be able to require anything. You mean this particular issue causes the require to not work? I've implemented a fix in #178, I'm just still working on getting the tests passing in all environments. It's taking awhile to get everything straight because it's an issue that only occurs in certain versions of v8.

fwiw, this issue is fixed in node 6.1: https://travis-ci.org/trailsjs/trails/jobs/128461428#L448

**Comment by jaumard** [comment]
No angular2 is not 'requirable' at all, in any js files you can't do `require('angular2')` or you have ` Cannot find module 'angular2'`. It's another issue than this one but I put it here because it's related.

**Comment by jaumard** [comment]
@tjwebb try it yourself when you can here https://github.com/jaumard/trails-express-gulp-angular-2 `npm i` and `npm start` you will see the problem.

**Comment by jaumard** [comment]
I fix the problem like this : 
```
const ignoreModule = modules.find(moduleId => {
        try {
          return require(moduleId) === prop
        } catch (err) {
          return false
        }
      })
```
