### ISSUE TITLE
Slush.js instead of Yo?

### ISSUE THREAD

**Issue by kokujin** [trailsjs/trails#18]
Was'nt there a discussion about using Slush instead of Yo a while back? It was based on the usage of Grunt vs. Gulp. Since most people are migrating to Gulp, it would be nice if Trails used Slush instead.

**Comment by tjwebb** [comment]
Can you elucidate the difference between Slush and Yo, and how Gulp/Grunt fit into this? I do not know what Slush is.

**Comment by kokujin** [comment]
Hey Tj, I think the site says it all, http://slushjs.github.io/#/, "The streaming scaffolding system.
Gulp as a replacement for Yeoman". 

I thought it would be a better choice since Trails uses Gulp. I use Gulp in all my projects.

**Comment by tjwebb** [comment]
Trails doesn't use gulp at the moment, but it can. I think for the alpha we'll support yeoman just because it's already working. If you'd like to help out with adding slush support before our 1.0 release, we can work that in. Let me know.

**Comment by DaAwesomeP** [comment]
+1 for Gulp. I don't know about Slush though.

**Comment by jaumard** [comment]
@DaAwesomeP here is for gulp https://github.com/YannBertrand/trailpack-gulp :)

**Comment by scott-wyatt** [comment]
This may be a handy resource for this discussion http://www.slant.co/versus/5082/5085/~yeoman_vs_slush Slant.co community still votes yeoman as the number 1 workflow wrapper (out of 79 people lol).

Personally, for the generation of trails apps, yo seems to work great and is easy to maintain, however, I can see people finding slush useful in their personal apps.

**Comment by tjwebb** [comment]
I think we're going to stick with yeoman for the main trails generator. Due to the modularity of the ecosystem, I'm happy to link to other generators from the community if someone would like to contribute this work. Thanks.
