### ISSUE TITLE
Archetype package with last versions

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#195]
#### Issue Description
Currently modules version are hard coded here https://github.com/trailsjs/trails/blob/master/archetype/package.json#L9-L16v
Maybe we can replace all version by `latest`, like this the generator will always install last npm versions for all modules.

#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by tjwebb** [comment]
This won't work when we need to manage multiple versions of Trails in the wild. e.g., `generator-trails` version 1.x.x should only install Trails 1.x, and `generator-trails` 2.x should install Trails 2.x. The user should be able to choose a generator version that matches the version they want to install.

**Comment by jaumard** [comment]
So the solution here is to update the archetype each time a new version of a dependency is release ? 

Currently the generator install trailpacks (the ones no under the package.json) with @latest so it doesn't know if versions are compatible with the v1 or v2 of trails... It just install last version. 
That's why I ask to put `latest` by default for now and we will see how we can handle this for the v2. At least we have a v1 up to date who is working after a fresh generation.

**Comment by jaumard** [comment]
Need a new version on npm before closing this issue @trailsjs/maintainers
