### ISSUE TITLE
Unable to generate a Trails project with Yo

### ISSUE THREAD

**Issue by KevinNTH** [trailsjs/trails#197]
#### Issue Description
**Unable to generate a Trails project with Yo.**
I just install `yo` and `generator-trails`. Then, I execute this command `yo trails`. I enter my options and nothing happens after the module name option. 

![trails generator](https://cloud.githubusercontent.com/assets/1632391/15290941/d98dc518-1b7b-11e6-9b5c-874061c233f7.png)

#### Environment
- node version: v6.1.0
- trails version: ???
- operating system: Windows 10 64bits

**Comment by KevinNTH** [comment]
I just test with `node v4.4.4` and `npm v3.9.0` and this is still not working.

**Comment by jaumard** [comment]
Thanks ! I will take a look ! :) Currently Trails v1.0 is out but some Trailpacks are not compatible yet and need to be updated. I'll keep you updated ;)

**Comment by jaumard** [comment]
Don't know why under windows it freeze after module name if name already exist on npm repository. If it's not the process end without error after "Package keywords"  but nothing was generated... 
 
![capture d écran 2016-05-16 a 17 37 14](https://cloud.githubusercontent.com/assets/2970449/15294532/ef5a2c36-1b8c-11e6-9c59-623a2d06bd5a.png)

Seems like the generator is not compatible with windows at all...

**Comment by jaumard** [comment]
Just some more tests, it appear to block on mac too with last `yo` (1.8.1). `yo@1.7.0` works fine.

**Comment by tjwebb** [comment]
So this only happens after upgrading to `yo` 1.8.x?

**Comment by jaumard** [comment]
@tjwebb in windows the generator just not works... on mac after upgrading in 1.8 there some problems. That's why I update `generator-node` but can't publish it on npm (travis fails). 
I currently trying to make `generator-node` work on appveyor, maybe it will fix all windows problems also. But the current master should fix all mac problems

**Comment by jaumard** [comment]
@tjwebb ok now `generator-node` is green on windows ! https://github.com/trailsjs/generator-node can you take a look to deploy it on npm ? I will continue to look `generator-trails` once the new `generator-node` is deploy. Thanks

**Comment by KevinNTH** [comment]
Hi,

I just tried trails on my linux distribution.
When I generated the app with `yo trails` and my directory and module name is **trails**, the generator script loops.
Then, I try again with a different directory and module name **trails-test**, there is no problem.

Shall I open another issue for this ?

Anyway, I hope the problem on Windows will be fixed :D
Many thanks.

**Comment by jaumard** [comment]
@KevinNTH no need another issue thanks ! I'm on it :D all should be fix with the next `generator-node` version for linux/mac, don't know for windows yet ^^
Keep you updated when the new version is out.

**Comment by jaumard** [comment]
@KevinNTH this is normally fix with `generator-trails@1.0.0` can you test please ? I also made a test with it on mac and windows and it was successful ! :D 
Let us know :)

**Comment by KevinNTH** [comment]
@jaumard thanks for your contribution !

... but... :P

On Linux, node v6.1.0 : 
* mkdir trails ; cd trails
* yo trails
>>>
```
│ Update available: 1.0.0 (current: 1.0.0-beta-7) │
│ Run npm update -g generator-trails to update.
```
I update my generator, then execute `yo trails` again.

And I still block at the module name option (which I enter default value **trails**).

**Comment by jaumard** [comment]
@KevinNTH ok thanks! I think this will be resolved by `generator-node` (I'm waiting the new version on npm) but v1.0.0 have now to work correctly now on windows (and mac/linux) (if the name is not already on `npm` or it will freeze). Can you confirm please ?

**Comment by KevinNTH** [comment]
@jaumard : Yes, I understand now "if the module name is already on `npm` it will freeze".

On linux, the generator works !
I am going to try on Windows later and keep update you !

**Comment by KevinNTH** [comment]
Ok, everything is fine on **Windows 10**, thanks a lot for the fix !!! I needed it :D

**Comment by jaumard** [comment]
@KevinNTH thanks for the confirmation ! :D great so now we just need new `generator-node` to fix the freeze and it will be perfect. Little up @tjwebb if you can take a look at travisCI for `generator-node` :)

**Comment by jaumard** [comment]
Thanks @tjwebb but now I have this problem when I try to npm install `generator-node` : 
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@trails/generator-node"
npm ERR! node v4.3.1
npm ERR! npm  v3.9.0
npm ERR! path /Users/jaumard/IdeaProjects/generator-trails/node_modules/.staging/lodash-51519aac
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/jaumard/IdeaProjects/generator-trails/node_modules/.staging/lodash-51519aac' -> '/Users/jaumard/IdeaProjects/generator-trails/node_modules/@trails/generator-node/node_modules/generator-license/node_modules/lodash'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/jaumard/IdeaProjects/generator-trails/node_modules/.staging/lodash-51519aac' -> '/Users/jaumard/IdeaProjects/generator-trails/node_modules/@trails/generator-node/node_modules/generator-license/node_modules/lodash'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaumard/IdeaProjects/generator-trails/npm-debug.log

```
Any idea ?

**Comment by jaumard** [comment]
@tjwebb related to this issu https://github.com/npm/npm/issues/5082
possible fix : 
https://github.com/npm/npm/issues/5082#issuecomment-217996678
https://github.com/yeoman/yo/issues/437#issuecomment-219977426

**Comment by jaumard** [comment]
@tjwebb I try to deploy from node 4 or 5 but same result... Same error but for a different submodule...

**Comment by jaumard** [comment]
I deploy `generator-trails@1.0.1` who use the working `generator-node@1.0.14` for now until we figure how to deploy `generator-node` correctly on npm.

**Comment by jaumard** [comment]
@KevinNTH normally now generator shouldn't freeze anymore if package already exist :) can you confirm ?

**Comment by KevinNTH** [comment]
@jaumard : Yes I confirm ! Thanks et nice job !!!

**Comment by jaumard** [comment]
Can be close @tjwebb @konstantinzolotarev :)
