### ISSUE TITLE
The localhost url with port should be printed with the "Basic Info"

### ISSUE THREAD

**Issue by KevinNTH** [trailsjs/trails#198]
Hi there,

I am a new comer to Trails. After executing for the first time `npm start`.
The localhost url with the port should be printed with the "Basic Info".
Indeed, I had no idea of what was the default port (which is 3000).

**Comment by jaumard** [comment]
Welcome @KevinNTH ;) 

Sound like a good idea to add the full url `http://localhost:3000` base on web config. 
Before the default log level was debug, on it you have the port number but with info you're right you doesn't have it.

maybe we can add `Application started at http://localhost:3000` or just add `Application root : http://localhost:3000 `...

**Comment by KevinNTH** [comment]
Yes something like that would be nice :)

Then, we will be able to ctrl+click and open the trails app into the browser !

**Comment by tjwebb** [comment]
> Then, we will be able to ctrl+click and open the trails app into the browser !

Ah yea, I like this idea as well.

**Comment by jaumard** [comment]
@wbprice take a look a this first :) https://github.com/trailsjs/trailpack-core/pull/53

**Comment by wbprice** [comment]
[trailsjs/trailpack-core#53](https://github.com/trailsjs/trailpack-core/pull/53) was merged, which fixes this.
