### ISSUE TITLE
Environment config problem

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#200]
#### Issue Description
If I put this under `config/env/production.js` : 

```
const winston = require('winston')

module.exports = {

  trailpack: {
    disabled: [
      'repl'
    ]
  },
  database: {
    /**
     * Define the database stores. A store is typically a single database.
     *
     * Use the SQLite3 by default for development purposes.
     *
     * Set production connection info in config/env/production.js
     */
    stores: {

      /**
       * Define a store called "local" which uses SQLite3 to persist data.
       */
      sqlitedev: {
        adapter: require('waterline-sqlite3'),
        migrate: 'safe'
      }
    },

    models: {
      defaultStore: 'sqlitedev',
      migrate: 'safe'
    }
  },

  web: {
    port: 8080
  },

  log: {
    logger: new winston.Logger({
      level: 'info',
      exitOnError: false,
      transports: [
        new winston.transports.Console({
          timestamp: true
        }),
        new winston.transports.File({
          name: 'info-file',
          level: 'info',
          filename: 'trails-info.log',
          timestamp: true
        }),
        new winston.transports.File({
          name: 'error-file',
          level: 'error',
          filename: 'trails-error.log',
          timestamp: true
        })
      ]
    })
  }
}
```

They are 2 problem : 

- Trailpack repl was not disable, `trailpack` field config seems ignored
- Config are not override the default `config/*`, it's replace it, this means I loose every config I put for `config.web` witch is for dev and prod, all I want to do is change the port number but everything else is lost.

#### Environment
- node version: all
- trails version: 1.0.0
- operating system: all

**Comment by tjwebb** [comment]
> Trailpack repl was not disable, trailpack field config seems ignored

Is this still documented somewhere? I think this feature was never implemented. I still want it, though.

> this means I loose every config I put for config.web witch is for dev and prod, all I want to do is change the port number but everything else is lost.

Crap, I bet this is happening here: https://github.com/trailsjs/trails/blob/master/lib/trails.js#L50. Right there, we really only want to merge the config sections that the Trails core knows about, which are only `main` and `log`.

We actually want to handle this here: https://github.com/trailsjs/trailpack/blob/master/lib/util.js#L43. Currently, only the trailpack's config.env is being merged into the pack's config. It should go ahead and do the same for the application config for the section(s) that Trailpack governs. Right now this is informally defined in the archetypes. Previously, the Trailpack would also define which config section that it `provides` (https://github.com/trailsjs/trailpack/commit/81016b044c07ff6aa32766b74fde9c5715ee4216#diff-4ac61d811c210f6b751340037a642caaL16) but I removed this from the docs because I didn't think we'd need it. Looks like I was right the first time.

**Comment by jaumard** [comment]
> Is this still documented somewhere? I think this feature was never implemented. I still want it, though.

@tjwebb no not documented but it's on the archetype here: 
https://github.com/trailsjs/trails/blob/master/archetype/config/env/production.js#L8 so I was thinking it works ^^ 

> Crap, I bet this is happening here: https://github.com/trailsjs/trails/blob/master/lib/trails.js#L50. Right there, we really only want to merge the config sections that the Trails core knows about, which are only main and log.

I understand so `envConfig ` should have only `main` and `log` and leave the rest. After this  https://github.com/trailsjs/trailpack/blob/master/lib/util.js#L43 will do his job I think but currently `pack.config.env` is never set anywhere (https://github.com/trailsjs/trailpack/blob/master/index.js#L47) so it will not work until this. Any idea how to initilize this ? Because we currently don't know the config key of each trailpack, it can be anything... Trailpack should set it somewhere we can use it... 
We also can disable trailpack at the same place (https://github.com/trailsjs/trails/blob/master/lib/trails.js#L50.) What do you think ? 

> Previously, the Trailpack would also define which config section that it provides (trailsjs/trailpack@81016b0#diff-4ac61d811c210f6b751340037a642caaL16) but I removed this from the docs because I didn't think we'd need it. Looks like I was right the first time.

I notice you remove this :D and I think it was a good idea to let choice to trailpack to provide or not api/config

**Comment by jaumard** [comment]
@tjwebb I just start a PR about this but don't understand why you want environment config merge here https://github.com/trailsjs/trailpack/blob/master/lib/util.js#L43 because actually this line don't merge trailpack environment config with user config but default trailpack config with environment config.

I will be more difficult to do here than do it https://github.com/trailsjs/trails/blob/master/lib/trails.js#L50 

Let me know what do you think, if you think my PR is correct I will have to make a PR for `trailpack` module too.

**Comment by jaumard** [comment]
Ok I have env config who is working with this PRs : 
https://github.com/trailsjs/trails/pull/203
https://github.com/trailsjs/trailpack/pull/32

Let me know your thoughts @tjwebb :)
