### ISSUE TITLE
Add snyk to travisCI to search for vulnerabilities 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#201]
#### Issue Description

https://snyk.io
Can be nice to set up snyk to every Trails modules to scan for vulnerabilities. We can also add a badge on Readme.

snyk search for vulnerabilities on all dependencies. Doesn't take a lot of time to set up and can prevent some security vulnerabilities.
#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by tjwebb** [comment]
Currently I'm using `nsp` to lookup known vulnerabilities. How does that compare to snyk?

**Comment by jaumard** [comment]
Didn't know `nsp` ! Thanks I'll take a look ^^ `snyk` is in beta for now but sound promising, it allow to search modules vulnerabilities :  example : https://snyk.io/test/npm/sails/ 

That can be useful to look at this before adding a new dependencies. It also allow you to analyse a github repo. Allow some badges for the Readme. 

Anyway `snyk` or `nsp` should set up with travisCI and vulnerably badge added on Readme for all Trails modules. Like this we can show to the community that security is taking seriously by the team. 
Also have a `security@trails.io` for reporting any security risk can be good to add on Readme.

**Comment by jaumard** [comment]
I just see that `nsp` is used by `snyk` under the hood and add more checks. 
So it can be better to use snyk :) 

Sources : http://blog.xebia.com/are-your-node-modules-secure/
https://twitter.com/fhemberger/status/687618488995811328

**Comment by tjwebb** [comment]
Ok cool. Removing `nsp` and using the snyk service will simplify some of the ecosystem test logic in smokesignals

**Comment by jaumard** [comment]
Can be nice if smokesignals throw an exception by default on vulnerabilities; like this it will fail the local unit tests when we dev and we can fit it right away. With an option (trailpack options pass on app config) to ignore vulnerabilities in case they're no choice...
