### ISSUE TITLE
generator dependency missing. can't install

### ISSUE THREAD

**Issue by tiny-byte** [trailsjs/trails#202]
#### Issue Description
I was trying to install trails, but says some dependency doesn't exist. how can I resolve this?
I am using node v6.1.0 on linux mint.
thanks in advance

Linux 3.13.0-37-generic
npm ERR! argv "/home/tinymint/node-versions/node-v6.1.0-linux-x64/bin/node" "/home/tinymint/node-versions/node-v6.1.0-linux-x64/bin/npm" "install" "-g" "generator-trails"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 no such package available : @trails/generator-node
npm ERR! 404 
npm ERR! 404  '@trails/generator-node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'generator-trails'

**Comment by jaumard** [comment]
Hum no problem normally https://travis-ci.org/trailsjs/generator-trails builds are all green. 
Try to clean npm cache and try again. Let us know.

**Comment by tiny-byte** [comment]
Looks like there was a problem with sinopia I was running, after disabling it, everything installed fine.
thanks

**Comment by facultymatt** [comment]
I had this problem because yo-doctor was failing because I was using npm 2.x.x. Upgrading to 3.x.x solved this problem for me.
