### ISSUE TITLE
Add tests suite environment initialisation to generator

### ISSUE THREAD

**Issue by tnunes** [trailsjs/trails#204]
#### Issue Description
I generated a new project with `yo trails` and then proceeded to generate my first model with `yo trails:model user`, which generated the user model and a unit test for it.

It seems to me that the generator is missing some files, since I can't run the tests by default with `npm test`, so I added a `mocha.opts` to the test folder that is now picking up the test (by using `--recursive`).

Now the user unit test is failing, since it's expecting a `global.app.api.models['User']` to exist, which doesn't.

Shouldn't the test scaffolding add some tests suite initialisation to expose the trails app in the global scope for the tests?

#### Environment
- node version: any
- trails version: 1.0.0-beta-1
- operating system: any

**Comment by tjwebb** [comment]
> Shouldn't the test scaffolding add some tests suite initialisation to expose the trails app in the global scope for the tests?

Yes, there's a gap where tests are correctly included for each generated controller/service/etc, but the necessary bootstrap logic isn't there for the tests to run correctly.

**Comment by tjwebb** [comment]
@tnunes If you're interested: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=34526924)](https://www.bountysource.com/issues/34526924-add-tests-suite-environment-initialisation-to-generator?utm_source=34526924&utm_medium=shield&utm_campaign=ISSUE_BADGE)

:)

**Comment by tnunes** [comment]
@tjwebb Cool!

Will it be enough to add the necessary logic to `archetype/test/` in this repository or do you think we need changes to `generator-trails`?

**Comment by jaumard** [comment]
@tnunes no you need to also update `generator-trails ` because for now it doesn't copy the `test` directory :) but it's 2 line of code to add ^^ these ones https://github.com/trailsjs/generator-trailpack/blob/master/src/app/steps/writing.js#L15-L16 lol

**Comment by tnunes** [comment]
@jaumard thanks! Will look into this after work today ;)

**Comment by tnunes** [comment]
Just submitted #207 and https://github.com/trailsjs/generator-trails/pull/56.

I can run my tests now ;)

**Comment by tnunes** [comment]
@tjwebb can you please take a look at #207? Thanks!

**Comment by tnunes** [comment]
@tjwebb can we merge the PRs and close this?

**Comment by catrielmuller** [comment]
@tjwebb I think we can close this issue
