### ISSUE TITLE
Trails docs are not accessible

### ISSUE THREAD

**Issue by tnunes** [trailsjs/trails#206]
When trying to browse the Trails docs, the server is returning 403.

e.g.: http://trailsjs.io/doc/config/database

**Comment by jaumard** [comment]
@tnunes it's because there actually no documentation :D 
there a start at https://github.com/trailsjs/trails-docs

**Comment by tjwebb** [comment]
@tnunes those URLs are placeholders until we get the website deployed. The trails-docs repo is where the docs currently live.

**Comment by scott-wyatt** [comment]
Hi everyone, the website is deployed, although it has some differences between v3 and v2.  I'm closing this for now, please feel free to reopen.
