### ISSUE TITLE
Trails compilers support

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#208]
#### Issue Description
Actually it's not possible to write Trails files (api/config) with TypeScript or CoffeeScript format. A trailpack can't do it because when Trails start nothing was load (because they are no JS files, only .ts or .coffee).

In order to fix this we can create `trails-compiler` module witch need to be override by `trails-compiler-typescript` and `trails-compiler-coffee` ... 

The Trails app is launch by `node server.js` so the first thing to do in `server.js` is to check if there a `trails-compiler`, if one (or more ?) is present `server.js` launch them to compile every sources into JS. Once compiled `server.js` can do like now and start the Trails app :) 

Some interface need to be think/create for `trails-compiler` in order to work correctly but like this Trails can be compatible with any JS derivate languages (even Dart if some are courageous lol).

For instance each `trails-compiler` will embed an `archetype` of Trails project (but in ts, coffee...) that can be use in the generator to generator a Trails project in ts, coffee... 

That's a start and it's an open discussion here ^^

**Comment by Alaneor** [comment]
I know it has been a somewhat common practice to do this kind of on-the-fly compilation but honestly, in the long run it always causes more harm than it brings good to a project.

Coffeescript is not JavaScript, nor is TypeScript. You would not try to run a C program which compiles to assembly at runtime in production, not even while developing.

The fact that these languages compile to JavaScript should be consodered an implementation detail and introduce a *compilation step* into the project which is necessary for the app's execution (i.e. via Gulp, Make, grunt, what have you).

**Comment by tjwebb** [comment]
Mostly agree with @Alaneor with a minor clarification:

It's policy of the Trails team that trailpacks can be built however, in whatever language, as long as they conform to the provided `Trailpack` interface at the end of the day. If your trailpack requires compilation/transpilation, that's perfectly fine, as long as the user (developer) doesn't need to be concerned with these details.

This discussion came up in Slack as we were discussion Angular 2, and how to build a Trailpack that makes using it easier, but also that incorporates support for TypeScript, since apparently all the Angular 2 docs are provided with TypeScript examples. I think a reasonable option might be to offer an easy way to configure `trailpack-webpack` to transpile, possibly. But ultimately, if a Trailpack requires that other application code uses something other than Javascript, that's something that's up to the developer to set up in their build process. I don't think that Trails can really have an opinion on this, because as @Alaneor pointed out, it's not a framework-layer concern, it's a concern of the build process.

**Comment by jaumard** [comment]
Yes my current needs is : I want to use Angular 2 with server rendering, to do that hapi/express need to be configured with some Angular2 things, so Trails config/api need to be in Typescript as it's the default "language" for Angular 2.

So if Trails files need to be in typescript (like in my current needs) `trailpack-webpack`, `trailpack-gulp` `trailpack-typescript` become useless to me (they can't compile server files as the server already started, it's too late and files will be ignored) and I have to use gulp/webpack outside Trails. 
That's the official way we want ?

**Comment by maissani** [comment]
@jaumard ^^ Isomorphic trails-ng2 not for today ;)

**Comment by Alaneor** [comment]
@jaumard TypeScript cannot be run directly as-is, it also requires compilation. Which means, eventually, even Angular 2 project with server-side rendering must ultimately be compiled down do JS. So the preferred way (performance- and memory-wise) would be to compile your project from TS down to JS before you even start it.

**Comment by jaumard** [comment]
@Alaneor I know ^^ I currently test to create a Trails app in Typescript but when it's compiled into ES5 or ES6 it's not working at all when started : 

ES5 : 
```

error: 
 Error: DefaultService should be a class. It is a regular object
    at /Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/trailpack-core/lib/context.js:47:15
    at /Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/lodash/lodash.js:12739:23
    at /Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/lodash/lodash.js:2654:24)
    at Function.mapValues (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/lodash/lodash.js:12738:7)
    at Object.bindMethods (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/trailpack-core/lib/context.js:45:14)
    at Core.configure (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/trailpack-core/index.js:29:37)
    at /Users/jaumard/IdeaProjects/trails-angular2-isomorphic/node_modules/trails/lib/trailpack.js:63:26
    at process._tickDomainCallback (node.js:412:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
error: The application did not boot successfully.
error: Try increasing the loglevel to "debug" to learn more
mac:trails-angular2-isomorphic jaumard$ 
``` 

ES6 : 
```

/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/.tmp/build/api/controllers/DefaultController.js:3
class DefaultController extends trails_controller_1.default {
                                                   ^

TypeError: Class extends value undefined is not a function or null
    at Object.<anonymous> (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/.tmp/build/api/controllers/DefaultController.js:3:52)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/.tmp/build/api/controllers/index.js:2:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jaumard/IdeaProjects/trails-angular2-isomorphic/.tmp/build/api/index.js:2:23)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! trails-angular-2-isomorphic@0.0.0 start: `node .tmp/build/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trails-angular-2-isomorphic@0.0.0 start script 'node .tmp/build/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the trails-angular-2-isomorphic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .tmp/build/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs trails-angular-2-isomorphic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls trails-angular-2-isomorphic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaumard/IdeaProjects/trails-angular2-isomorphic/npm-debug.log
```

The project is here https://github.com/jaumard/trails-angular2-isomorphic maybe more typescript expert can help here ^^

**Comment by Alaneor** [comment]
Maybe try to set your compilation target to *es6*? It might be that classes are compiled down to some kind of generic object instead of a proper class.

Additionally, I saw some comments regarding this that you might additionally compile the sources twice - once from TS to JS (ES6) and then with Babel from ES6 to a nodejs-compatible variant of ES6 (ie. import statements to commonjs requires etc.).

**Comment by jaumard** [comment]
@Alaneor yeah agree for ES5 but I try ES6 too (the second output log) :) and no luck too because typescript add `.default` to extends and `exports`... If I manually fix those Trails compiled project start fine ^^. Maybe I miss some options.
I will look into babel also to see the `nodes-compatible variant of ES6` but I'm new to typescript and babel so I'm fishing here lol but thanks for the tips that's help ;)

**Comment by Alaneor** [comment]
Aaah well the `.default` thing is actually the correct behaviour of ES6 modules, Babel won't help here. 😄

I have a feeling that when you do `export default class MyController {}` or similar, Trails will not understand this because it does not expect an ES6 module, just a good ol' CommonJS module. The main difference is that a CommonJS module can consist of anything - an object, a class, a function, whatever you assign to `module.exports`. With an ES6 module, though, no matter how hard you try, you can only export a plain object with some properties.

So, when you `export default class Test {}`, and then you `require('test')`, you will get this:
```js
{ default: /* Test class here */ }
```

But Trails most likely expects the class to be the thing that is required and does not look at the `.default` property.

This cannot be fixed in your code. Trails would have to introduce support for ES6 modules. Not quite sure how to do that in a manner compatible with CommonJS modules because those two are fundamentally different.

**Comment by jaumard** [comment]
Hum I'm fucked ! lol Thanks for letting me know all of this ! Didn't know... 
Just for the record here is my controller in TS : 

```
'use strict'

import {Request, Response} from 'express'
import Controller from 'trails-controller'

/**
 * @module DefaultController
 *
 * @description Default Controller included with a new Trails app
 * @see {@link http://trailsjs.io/doc/api/controllers}
 * @this TrailsApp
 */
export default class DefaultController extends Controller {
  app: any;
  /**
   * Return some info about this application
   */
  info(req: Request, res: Response) {
    res.status(200).json(this.app.services.DefaultService.getApplicationInfo())
  }
}
```

Witch look like once compiled to : 
```
'use strict';
const trails_controller_1 = require('trails-controller');
class DefaultController extends trails_controller_1.default {
    info(req, res) {
        res.status(200).json(this.app.services.DefaultService.getApplicationInfo());
    }
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = DefaultController;
```

Where I need : 
```
'use strict';
const trails_controller_1 = require('trails-controller');
class DefaultController extends trails_controller_1 {
    info(req, res) {
        res.status(200).json(this.app.services.DefaultService.getApplicationInfo());
    }
}
module.exports = DefaultController;
```

**Comment by Alaneor** [comment]
@jaumard You could, in your *.ts* file, assign the class directly to `module.exports` instead of using `export default`, but I dunno if that's legal in TypeScript...

It should fix that issue, though!

**Comment by jaumard** [comment]
Clever :), in fact it fix half of the problem ^^ now compiled source look like this : 

```
'use strict';
const trails_controller_1 = require('trails-controller');
module.exports = class DefaultController extends trails_controller_1.default {
    info(req, res) {
        res.status(200).json(this.app.services.DefaultService.getApplicationInfo());
    }
};
```
The `.default` on the extends is always present... 

I come from the typings `.d.ts` file I create for `trails-controller` in order to TS to know about this module. It's look like : 

```
declare module "trails-controller" {
  export default class Controller {
    app:any;
  }
}
```
Not possible to put `module.exports` here...

**Comment by jaumard** [comment]
@tjwebb in order to be compatible with ES6 modules (and not be blocked in the future when ES6 module will be supported into node) can we refactoring `trails-controller`, `trails-model`, `trails-policy` and `trails-service` to export an object and not directly the class ? 
It can be useful to have multiple class support to : example for `trails-controller` it can export a `DefaultController` and a `TrailpackController` for standardized api.  

And that will fix my last problem (for now...) with typescript.

**Comment by jaumard** [comment]
Ok so I manage to make it work by playing with some typescript configuration, can't tell you really what fix it but now I can have a full fresh Trails project in TS and compile/run it. I think my way is not really fully typescript way because I don't use `import` but as @Alaneor `module.export` to _hack_ the `.default` problems.

For the curious https://github.com/jaumard/trails-angular2-isomorphic next step is to manage to adding a small angular2 app with server rendering.

**Comment by jaumard** [comment]
I manage to find why it's working now, it's because I use the flag `noLib` for typescript compiler options witch mean that no verifications was done on the TS code, it just compile it to ES6. Witch is fine for unlock me for now but not a solution to use Trails in typescript. I think every Trails module should be modify to be compatible with ES6 module.

**Comment by jaumard** [comment]
Closing this as we more (or less ^^) agree that task manager should be used to compile Trails before start it
