### ISSUE TITLE
when creating new project and try to start error Cannot find module 'colors'

### ISSUE THREAD

**Issue by ycpatel813** [trailsjs/trails#209]
#### Issue Description
 Every time need to install colors after using yo tails
``` javascript
C:\Users\Scw\Desktop\tra>node server.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous>  (C:\Users\Scw\Desktop\tra\node_modules\trailpackrepl\node_modules\big-tree-cli\index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
#### Environment
- node version: v4.4.4
- trails version: ^1.0.0-beta-1
- operating system: Window 7

**Comment by jaumard** [comment]
Also append on linux and mac https://travis-ci.org/trailsjs/trails/jobs/134332346#L1055 but only on node v4
Thanks for the report !

**Comment by tjwebb** [comment]
@ycpatel813 can you try installing npm3?

**Comment by ycpatel813** [comment]
@tjwebb i have installed npm3 still i face error
i give you more detail description 
when i create new project using yo trails project is created successfully...
after then i try npm start i face this error.

after some debug i found trailpack-repl/node_modules/big-tree-cli/index.js require "colors".
for solve that error i use ``` npm install --save colors``` and all working fine.

**Comment by jaumard** [comment]
@ycpatel813 can you test with the master branch please ? See if you have the same error

`npm i https://github.com/trailsjs/trailpack-repl`

**Comment by ycpatel813** [comment]
@tjwebb @jaumard  i have tested today with my friend pc which has linux os and its working fine in linux. so it may be my window problem but not sure.

**Comment by jaumard** [comment]
@ycpatel813  No it's not, it crash on Node v4 on linux and mac too on Travis. Did you test with the master ? Better?

**Comment by ycpatel813** [comment]
yes i have tested with master branch also still same result..

**Comment by jaumard** [comment]
ok thanks :) so I think best option is to add it on trailpack-repl dependencies... What do you think @tjwebb ? Don't understand why it's not installed because `big-tree-cli ` have `colors:"*"` on his dependencies...

**Comment by ycpatel813** [comment]
@jaumard today i tested with master branch error is resolved :+1:

**Comment by jaumard** [comment]
@ycpatel813 thanks ! I publish a v1.0.8 of trailpack-repl so this should be fix now :)

**Comment by jaumard** [comment]
Can be close @tjwebb @konstantinzolotarev :)

**Comment by konstantinzolotarev** [comment]
Nice !
