### ISSUE TITLE
validate logger level 

### ISSUE THREAD

**Issue by ycpatel813** [trailsjs/trails#213]
#### Issue Description

``` javascrpit
logger: new winston.Logger({
    level: 'debgu',
    exitOnError: false,
    transports: [
      new (winston.transports.Console)({
        prettyPrint: true,
        colorize: true
      })
    ]
  })
```

  by mistake i wrote dubgu in logger level after that trails app did not start and did not respose any error message
  so it is useful that trails validate logger level 
#### Environment
- node version: v4.4.4
- trails version: ^1.0.0-beta-1
- operating system: Window 7

**Comment by jaumard** [comment]
We have to find a way to test/detect this... Because we can't validate the logger level because the logger can be any logger (not Winston) and then level will be not defined.

**Comment by tjwebb** [comment]
Yea, this is hard. The `level` is being sent into Winston as an argument, and isn't directly accessible to the application.

**Comment by tjwebb** [comment]
Continued in #261.
