### ISSUE TITLE
Fixture on trailpack

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#215]
#### Issue Description
Actually all trailpacks do they're stuff on the `initialize` methods, witch is fine. But currently on my trailpack I need to create some fixture in database, I can't do it in the `initialize` because maybe the ORM is not ready yet...

So currently I'm doing this : 

```
initialize() {
    this.app.on('trails:ready', () => {//Here my ORM is OK 
      lib.Utils.loadFixtures(this.app).catch(err => {
        this.app.log.error(`Can't load fixtures because of : `)
        this.app.log.error(err)
      })
    })

    return Promise.resolve()
  }
``` 

It does the job but it can be nice to doesn't start the server if fixture can't be loaded in DB, currently I just can log the error (or dirrectly call `app.stop()` but don't find this clean...)

Any thought ?

#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by jaumard** [comment]
@tjwebb does the `config/trailpack:lifecycle:initialize:listen` is implemented yet ? It's working but I don't know if I'm lucky or if it correctly wait the event :)

**Comment by scott-wyatt** [comment]
@jaumard, i'm going through some older issues and wanted to know if this one is still a problem?

**Comment by jaumard** [comment]
It's look like it's works so no problem anymore
