### ISSUE TITLE
Documentation Proposal for Trailpacks that deal with models

### ISSUE THREAD

**Issue by scott-wyatt** [trailsjs/trails#217]
#### Issue Description

Documentation Proposal

A tremendous difference between Trails and let's say Sails, is the ability to use many different ORMs. That said, I would like to propose that a guideline be added to trailpacks that deal with models.  They should list their supported ORMS like so:

| Repo | Build Status (edge) |
| --- | --- |
| [trailpack-waterline](https://github.com/trailsjs/trailpack-waterline) | [![Build status](https://img.shields.io/travis/trailsjs/trailpack-waterline/master.svg?style=flat-square)](https://travis-ci.org/trailsjs/trailpack-waterline) |
| [trailpack-sequelize](https://github.com/trailsjs/trailpack-sequelize) | [![Build status](https://img.shields.io/travis/trailsjs/trailpack-sequelize/master.svg?style=flat-square)](https://travis-ci.org/trailsjs/trailpack-sequelize) |
| [trailpack-js-data](https://github.com/scott-wyatt/trailpack-js-data) | [![Build status](https://img.shields.io/travis/scott-wyatt/trailpack-js-data/master.svg?style=flat-square)](https://travis-ci.org/scott-wyatt/trailpack-js-data) |

[Here is an Example](https://github.com/scott-wyatt/trailpack-stripe#supported-orms)
#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by jaumard** [comment]
100% for it :) nice and clear ^^ love it
Same can be done for webserver support for now hapi and express but much more in future.

Also Trails at the end have to provide a way to have unified API for Trailpacks I already do my proposal for policies/controllers on trailpack-controller and trailpack-polcies. trailpack-model have to be discuss too but @tjwebb mention that the common interface for models can be GraphQL and each trailpack ORM will have to do the translation into his native API. Like this this kind of badges will become useless :)

**Comment by maissani** [comment]
+1 I agree with that convention.

**Comment by scott-wyatt** [comment]
Closing this for now, we should move this over to https://github.com/trailsjs/trails-docs
