### ISSUE TITLE
get something minimal at trailsjs.io

### ISSUE THREAD

**Issue by vinyll** [trailsjs/trails#22]
Hey, right now the trailsjs.io shows a domain parking page.
That's pretty fancy and ugly..
For sure a waiting page or something redirecting to the Github would be better.

**Comment by kokujin** [comment]
+1

**Comment by tjwebb** [comment]
Yes, we'll try to have a basic site up before the alpha release in January. @yejodido is working on some ideas. If all else fails, I'll put up an RTD site: https://readthedocs.org/ :)

**Comment by vinyll** [comment]
I guess having a RTD there makes sense.

**Comment by kokujin** [comment]
+1

**Comment by remzr7** [comment]
+1

**Comment by scott-wyatt** [comment]
Site is up, the docs are for v3 which we will release soon, closing this for now. Please reopen if you please.
