### ISSUE TITLE
Trails silently fail when run with docker

### ISSUE THREAD

**Issue by Kennyomg** [trailsjs/trails#222]
#### Issue Description
I use trailpack-sequelize and trailpack-express v5 (chosen during setup) and using a mysql database.
I can run my project without docker and it just works as expected, but when I build an image in docker and try to run it, it just fails without error after express::Initialized then unloads the trailpacks and quits.
I think it fails during the initialization of trailpack-sequelize because sequelize::Initialized would be the next message.

When I put in incorrect login or host data in the sequelize config it prints out the error message that the given data is incorrect.

My other projects with express v4 and sequelize works as expected with docker.
I have tested this on Windows 10 Home edition (it runs docker with virtualbox since Hyper-V is windows 10 Professional only and I tried it with ubuntu (both client version and server version) which runs docker on it's own operating system.

#### Environment
- node version: 6.3.0
- trails version: ^1.0.0-beta-1
- operating system: Windows 10 home edition, Ubuntu 14.0.4

> ...
> [debug]: trails event: webserver:http:ready
> [debug]: trails event: trailpack:express:initialized
> [error]: The application did not boot successfully.
> [error]: Try increasing the loglevel to "debug" to learn more
> [debug]: trails event: trails:stop
> [info]: Shutting down...
> ...

**Comment by jaumard** [comment]
Hi @Kennyomg, I never use Trails and docker together but this kind of error look similar to the one some have with deploying on heroku, they had to disable the `trailpack-repl` in order to deploy correctly on heroku. Maybe you can try this. 

Also don't hesitate to update your trails version as the current version is `1.0.4`.

**Comment by gliwka** [comment]
@Kennyomg, disabling trailpack-repl does the job.

Best,
Matthias

**Comment by Kennyomg** [comment]
Thanks, works like a charm

**Comment by jaumard** [comment]
@maissani we should add a section on documentation about this :) heroku, docker or other services like this need to have repl disabled

**Comment by gliwka** [comment]
How about a change in trailpack-repl to add a check, if it's a real terminal or just a redirect (heroku, docker)?

Should be as easy as:
`if (process.stdout.isTTY)) {
  console.log('Direct TTY access, we can do REPL!');
}
else {
  console.log('No REPL');
}`

**Comment by jaumard** [comment]
Did you test this? If it's works yeah it could be something interesting to include I think! 
@tjwebb thoughts?

**Comment by gliwka** [comment]
Works like a charm, even in edge cases, i.e. using it with grep:

![image](https://cloud.githubusercontent.com/assets/4993665/17701872/d6435056-63cb-11e6-9d54-c4d2163eb99f.png)

**Comment by jaumard** [comment]
Cool :) I'll try to make a PR with this
Thanks!

**Comment by gliwka** [comment]
This also fixed #218.

**Comment by tjwebb** [comment]
@jaumard was a PR merged for this issue already?

**Comment by jaumard** [comment]
no @tjwebb PR is pending here https://github.com/trailsjs/trailpack-repl/pull/38
