### ISSUE TITLE
Uniform ORM trailpack event

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#223]
#### Issue Description

Currently each trailpack ORM fired `trailpack:ormName:event` it would be nice for trailpacks that support multiple ORM to have a unified `trailpack:orm:event` fired by `trailpack-datastore` 

Or allow to add in `config/trailpack.js` something like : 

```
initialize: {
      listen: [
        'trailpack:sequelize:initialized',
        'trailpack:waterline:initialized'
      ],
      emit: []
    }
```

And if `trailpack:waterline` is not installed the entry is ignored (with a log warning).
#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by konstantinzolotarev** [comment]
@jaumard I'd suggest to add `trailpack:orm:event` into all orm trailpacks. I think it makes more sense than creating list of weird events in trails.

**Comment by jaumard** [comment]
That's what I said, but in order to have multiple  ORM support in near futur it would be nice to keep the currents event also to know witch ORM fired events because `trailpack:orm:event` will be fired multiple times. Finally we just add `trailpack:orm:event` and didn't create anything weird right ?

**Comment by konstantinzolotarev** [comment]
Totally agree. 
For several ORMs - it wouldn't be default behavior. So decision will be on developer what orm event does he need.

**Comment by jaumard** [comment]
Related to https://github.com/trailsjs/trails/issues/194 should be also planned for v3 I think. Or we can set it as fix by @catrielmuller 's PR :) what do you think @tjwebb  ?

**Comment by scott-wyatt** [comment]
Closing as merged.  Please feel free to reopen.
