### ISSUE TITLE
How to call logger?

### ISSUE THREAD

**Issue by sschimmel** [trailsjs/trails#226]
Question to the more experienced with Trails. How am I supposed to call the logger? 

These options don't work when call from a controller:
- app.log --> undefined
- this.app.log --> undefined
- this.app.config.log --> not a function
- this.app.config.log.debug --> not a function

I'm using express 5.

**Comment by jaumard** [comment]
From a controller (whatever web server you use) you can do : 
- this.log.debug
- this.app.log.debug
- this.app.config.log.logger.debug

Work with warn, error, info... if you use the default winston logger that come with Trails.

**Comment by sschimmel** [comment]
Thank you, works like a charm.
