### ISSUE TITLE
Trails don't apply env configs for database

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/trails#228]
#### Issue Description
In all environments trails uses default configuration for `app.config.database.stores`

#### Environment
- node version: 5.12/6.3/6.4
- trails version: 1.0.4
- operating system: OSX

**Comment by konstantinzolotarev** [comment]
Related to https://github.com/trailsjs/trailpack-mongoose/issues/16

**Comment by scott-wyatt** [comment]
In js-data trailpack this is also not an issue, but it also doesn't seem likely that mongoose would get a different config then what trails gives it. @trailsjs/maintainers  Anyone else having this issue on their ORM?

**Comment by jaumard** [comment]
@tjwebb @scott-wyatt @konstantinzolotarev I think it's just a dependency problem `trailpack-datastore` need to be 1.0.2 witch is not the case for `trailpack-mongoose` and `trailpack-waterline` and both have problems. It worth the try :)
