### ISSUE TITLE
Env config

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#231]
#### Issue Description
Currently trailpacks are in charge to merge there env config (here https://github.com/trailsjs/trailpack/blob/master/lib/util.js#L43) but this come with some problems and this need to be change to be more simple for users.

Problems : 
- Only config files that belong to trailpacks are merge by environment, others are ignored
- When developing a trailpack, users must add there config files into there `config` folder or env config is ignored for those files

Solution : 
Trails should merge env config when it merge log/main config here https://github.com/trailsjs/trails/blob/master/lib/trails.js#L29

Related to : 
https://github.com/trailsjs/trails/issues/228

#### Environment
- node version: all
- trails version: all
- operating system: all

cc @konstantinzolotarev @tjwebb

**Comment by jaumard** [comment]
Those PRs fix this issue and are ready to merge @trailsjs/maintainers : 
https://github.com/trailsjs/trailpack/pull/38
https://github.com/trailsjs/trails/pull/230

**Comment by jaumard** [comment]
This PR need to be merged too trailsjs/trailpack#38 because currently env config are merged twice...

**Comment by catrielmuller** [comment]
Closed because the https://github.com/trailsjs/trailpack/pull/38 are merged.
And is solved in https://github.com/trailsjs/trails/issues/230
