### ISSUE TITLE
Transpile to ES5 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#233]
#### Issue Description

In the README we said we can transpile Trails app into ES5 (see https://github.com/trailsjs/trails/blob/a89e3aa5841b24974a6bc52ff4cb4b9bcb354a90/README.md#q-why-does-trails-require-node-4).
Transpile into ES5 is also very useful when working with Angular 2 and server rendering witch force you to use Typescript or ES7.

Currently Trails app transpiled into ES5 doesn't start because of this line : 
https://github.com/trailsjs/trailpack-core/blob/master/lib/context.js#L47
When transpiled into ES5 there no more classes and Trails throw an error.

Now Angular 2.0 is officially out, we should fix this :) 
#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by tjwebb** [comment]
If you transpile a class, it should turn it into a function, not an object. So `_.isPlainObject` should still return false. Can you elaborate?

**Comment by jaumard** [comment]
That's actually my problem :) can we replace `_.isPlainObject` by `_.isPlainObject || _isFunction` or something like this ? Because if we want Trails to run in ES5 we have to modify this test to doesn't throw an error.
If we change the test Trails can be transpile into ES5 same as Angular2 and it will be more easy to do server rendering. (actually it's quite pain in the ass to do it ^^ right @scott-wyatt ? lol)

**Comment by tjwebb** [comment]
What I'm saying is that if you want to define a controller/service class using ES5 syntax, you should just create an old-fashioned es5 class per usual:

```js
function MyController () { }
MyController.prototype.myHandler = function (request, reply) {
  // ...
}
```

Trails still treats them as classes and tries to instantiate them with `new`, so removing this check will just lead to a problem here: https://github.com/trailsjs/trailpack-core/blob/master/lib/context.js#L50.

Am I still not understanding? Do you have an example of what you're trying to achieve?

**Comment by jaumard** [comment]
My problem is not to right Trails part in ES5, is to transpile it into ES5 from TS (or whatever) @tjwebb.
 
Here is a quick example of what I'm trying to achieve https://github.com/jaumard/trails-ts 
Basically everything is in TS (needed by angular 2 if you want server rendering, it can be done without Trails in TS but it's far from an easy task @scott-wyatt and I can talk about it lol) 
It appear there some problems once transpile into ES5, maybe it's my configuration or maybe Trails need some work to run into ES5 after transpile.

The example just need `npm i` `npm start` to work, there some warnings but don't care it do the job ^^

**Comment by tjwebb** [comment]
@jaumard what's the latest status on this?

**Comment by jaumard** [comment]
I update the example but look like it's still not able to transpile into ES5: 

```
/Users/jaumard/TrailsProjects/trails-ts/dist/api/services/DefaultService.js:17
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^

TypeError: Class constructor TrailsService cannot be invoked without 'new'
    at new DefaultService (/Users/jaumard/TrailsProjects/trails-ts/dist/api/services/DefaultService.js:17:42)
    at _.mapValues (/Users/jaumard/TrailsProjects/trails-ts/node_modules/trails/lib/core.js:63:19)
    at /Users/jaumard/TrailsProjects/trails-ts/node_modules/lodash/lodash.js:13379:38
    at /Users/jaumard/TrailsProjects/trails-ts/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/jaumard/TrailsProjects/trails-ts/node_modules/lodash/lodash.js:3001:24)
    at Function.mapValues (/Users/jaumard/TrailsProjects/trails-ts/node_modules/lodash/lodash.js:13378:7)
    at Object.bindMethods (/Users/jaumard/TrailsProjects/trails-ts/node_modules/trails/lib/core.js:58:14)
    at TrailsApp (/Users/jaumard/TrailsProjects/trails-ts/node_modules/trails/index.js:147:43)
    at Object.<anonymous> (/Users/jaumard/TrailsProjects/trails-ts/dist/server.js:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

**Comment by KevinGruber** [comment]
@tjwebb It would be really awesome to change that check, so it can be compiled from Typescript.
I also ran into that problem. And i don't want to have a fork of the project just because 1 Line of code, as it as far as i can see wouldn't change anything except get TS working. Or am i wrong and i am not taking something into account?

BR,
Kev

**Comment by scott-wyatt** [comment]
Personally, we just transpile browser code to es5 and let the server stay in es6 which is how we deal with SSR in typescript/angular 2+. We are using this in production and it works quite well.

**Comment by KevinGruber** [comment]
@scott-wyatt ah so you set your transpire target of ts to es6? That could work actually and I never thought about that. I am actually not using SSR but I want to write my code in ts because I want the static typing.

BR
Kev

**Comment by jamrizzi** [comment]
I know how to prevent the `TypeError: Class constructor TrailsService cannot be invoked without 'new'` error. It at least worked with my specific configuration of trails.

https://github.com/jamrizzi/trailblazer

Install babel-core
```sh
npm install --save babel-cli
```

Add the following Babel configuration to your package.json
```js
. . .
  "babel": {
    "presets": [
      "node6",
      "stage-2"
    ]
  }
```

Then start the application using the babel-node
```sh
node ./node_modules/babel-cli/bin/babel-node server.js
```

**Comment by scott-wyatt** [comment]
v3 will be using node 7.6 and higher which will make this ability a default, I'm going to close this for the time being as I don't suspect there is a better answer than @jamrizzi's for v2.
