### ISSUE TITLE
Add pre commit eslint hook on all Trails repo

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#238]
Can be very nice to add this, it will prevent user to commit with eslint errors and then fail on Travis... 
Maybe we can use https://www.npmjs.com/package/precommit-hook-eslint

**Comment by troy0820** [comment]
You can also just use `pre-commit:` https://www.npmjs.com/package/pre-commit
which I've used and put the following in the pre-commit object in the `package.json`
That way, it can just be more than the eslint.  You can put esformatter there, etc.....
```
"scripts": {
"test": whatever you use to test
"lint": "eslint . --ext .js"
},
"pre-commit": ["lint", "test" ] 
```

**Comment by jaumard** [comment]
@troy0820 +1 for this solution ! We can also force tests to pass on some repo :)

**Comment by tjwebb** [comment]
eslint is already part of `npm test`, so CI should not pass if eslint fails. If any projects are not running eslint as part of the tests, they should be.

**Comment by jaumard** [comment]
Right @tjwebb but having pre commit hook can prevent noisy commits just to fix eslint issue or wait CI to fail because of eslint (because they are really slow...) can make the all process more clean ^^ that's my opinion after contribute to ng2-bootstrap where they use this :) can be a cool things to have

**Comment by tjwebb** [comment]
Makes sense. If there's an npm module that can set this up, I'm all for it.
