### ISSUE TITLE
validate integrity of trailpack lifecycle before booting

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#24]
Analyze the trailpack `lifecycle` configurations, and determine whether the trailpacks will load correctly, or if there is a mismatch in the lifecycle config (e.g. if a trailpack requires an event that no other configured trailpack intends to emit)

**Comment by jaumard** [comment]
It can be nice to do this only once a new trailpack is install. Because if there a lot of trailpacks it will slow down server start, it can be done on `npm install` or trailpack order can be save in a file/db a calculate only once.

**Comment by tjwebb** [comment]
Yea I think we can just do this when trailpacks are installed, since that's the only time this could change.
