### ISSUE TITLE
lib.Pathfinder Lifecycle #isComplete should execute in under 5ms

### ISSUE THREAD

**Issue by catrielmuller** [trailsjs/trails#243]
#### Issue Description

In some cases the travis ci test breaks cos this test fail.
Example: https://travis-ci.org/trailsjs/trails/jobs/165140454

I do not see the advantage of measuring performance on a server that does not have the resources dedicated to the test. This means that in some occasions (almost always) the test fails because the server is more saturated.
I propose that we increase the time of the tests (5ms to 15ms and 2ms to 6ms), or simply remove these tests.
#### Environment
- node version: 4.x
- trails version: 1.1.0
- operating system: OSX

**Comment by jaumard** [comment]
I think those tests are nice to have but should be tested locally only not under CI witch is not stable.

**Comment by tjwebb** [comment]
Yea, hosted CI won't be a reliable way to test this. Perhaps we can keep these tests, but separate them into a separate test suite. e.g., `npm run performance-tests`?

**Comment by catrielmuller** [comment]
Perfect let me do that
