### ISSUE TITLE
What about 2.0 LTS?

### ISSUE THREAD

**Issue by udanpe** [trailsjs/trails#248]
ROADMAP.md v2.0 LTS (October 2016)

**Comment by tjwebb** [comment]
We're still working on it, it will likely be a couple weeks late. (the 1.0 release was also about 2 weeks late). It's my fault, I hope to wrap it up by the end of next week.

**Comment by udanpe** [comment]
What about website with documentation? I think work in Sails had a bad effect on you) so slowly..

**Comment by Nishchit14** [comment]
@tjwebb I can help in documentation website, Please let me know how's it going and which process we're following for documentation.

**Comment by scott-wyatt** [comment]
@Nishchit14  this is where they live now https://github.com/trailsjs/trails-docs. You might ask @jaumard and @maissani on that repo?

**Comment by scott-wyatt** [comment]
Closing this, track #257 for more info.
