### ISSUE TITLE
Combine trailpack-core with Trails itself

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#252]
#### Issue Description
trailpack-core doesn't need to exist. Combining it with the core would reduce project management overhead, uneeded log output, and simplify some of the code in trailpack-core.

**Comment by tjwebb** [comment]
In progress

**Comment by jaumard** [comment]
Why trailpack-core was bumped into v2 ? if it's merge into Trails...

**Comment by tjwebb** [comment]
trailpack-core is now a no-op. It will be deleted entirely in v3.0, but will remain until then so that applications don't immediately break when upgrading to 2.0.

https://github.com/trailsjs/trailpack-core#note-this-pack-is-deprecated-as-of-trails-v20
