### ISSUE TITLE
add "deploy to heroku" button

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#26]
like https://github.com/keystonejs/keystone

**Comment by mikehostetler** [comment]
Need to specify an `app.json` file, as described here: https://devcenter.heroku.com/articles/heroku-button

Then, we'll need to deploy a generated repo, not the core repo. After that should be pretty straightforward.

**Comment by tjwebb** [comment]
> Then, we'll need to deploy a generated repo, not the core repo

Yea maybe we can deploy trails-example-app, or some derivative

**Comment by jaumard** [comment]
:+1: for trails-example-app but need some default views cause for now trails-example-app is only a generator-trails output.

**Comment by tjwebb** [comment]
We should create a todomvc app: http://todomvc.com.

**Comment by mikehostetler** [comment]
All great ideas, I'll start pondering and make a plan here.

--
Sent from mobile so please excuse the brevity or typos




On Tue, Jan 5, 2016 at 12:05 PM -0800, "Travis Webb" <notifications@github.com> wrote:












We should create a todomvc app: http://todomvc.com.

**Comment by jaumard** [comment]
todomvc is more for front end framework/library than back end as I see. If we want to do it we have to choose a front framework who will already be on todomvc.

**Comment by tjwebb** [comment]
> If we want to do it we have to choose a front framework who will already be on todomvc.

We can just use React. An example can't cover everything, but I think a react + trails example will give people an idea of how trails is used and how to get started.

**Comment by nrempel** [comment]
I think todomvc only makes sense for front-end frameworks. IMO, you'd be much better off with an example blog app or example twitter clone.

**Comment by jaumard** [comment]
Here is a todo app base on the http://todomvc.com that use Trails and Angular 2
https://github.com/jaumard/trails-todo-app-angular2

**Comment by wbprice** [comment]
And a React + Redux version: https://github.com/trailsjs/trails-todo-app

**Comment by scott-wyatt** [comment]
This is a bit stale, I think there have been some wonderful community builds, so I'll close this for now. Please feel free to reopen!
