### ISSUE TITLE
Build Failing on Linux / Mac on Travis CI because of a missing dependency

### ISSUE THREAD

**Issue by gunish** [trailsjs/trails#263]
#### Issue Description
The Build is failing on the Linux / Mac on Travis CI because of a missing dependency, according to logs. 

#### Environment
- node version: 4,5,6,7
- trails version: 2.0.0-rc3
- operating system: Linux / Mac 

![screen shot 2016-11-24 at 11 18 07](https://cloud.githubusercontent.com/assets/1183862/20596795/0f717f8c-b238-11e6-8285-c2e7581e842f.png)

**Comment by tjwebb** [comment]
are you still seeing this?

**Comment by jaumard** [comment]
Should be ok now, don't hesitate to reopen if it's still a problem
