### ISSUE TITLE
Reference error when running tests.

### ISSUE THREAD

**Issue by wbprice** [trailsjs/trails#264]
#### Issue Description
When running `npm test` all of my generated tests (model, controllers, etc) fail with messages like ```TypeError: Cannot read property 'api' of undefined```.  Suggests that the server isn't starting or I'm getting a reference error for some other reason.

#### Environment
- node version: v6.9.1
- trails version: trails@1.1.0
- operating system: MacOS

**Comment by jaumard** [comment]
Should be fix now if new version was deployed on npm

**Comment by scott-wyatt** [comment]
Closing for now, please feel free reopen if this is still an issue :-)
