### ISSUE TITLE
Session authentication

### ISSUE THREAD

**Issue by s-devaney** [trailsjs/trails#27]
I don't know if such functionality is outside of the scope of this project but sails-auth was a popular module in sailsjs. Could we improve on it in Trails and perhaps bake it into the core framework? Let's face it, the majority of apps will use it.

I propose we have a token based authentication strategy in Tails.

**Comment by tjwebb** [comment]
@s-devaney definitely! We are/were the maintainers of sails-auth, and will be migrating that functionality over to Trails (along with sails-permissions as well).

For more info: https://github.com/tjwebb/sails-auth/issues/118

**Comment by scott-wyatt** [comment]
There is now trailpack-acl and trailpack-passport released, though I agree we could get them into the trails namespace.  Since this functionality is now broadly considered a trailpack request, I'm closing this for now.  Please feel free to reopen!
