### ISSUE TITLE
Support for Restify server

### ISSUE THREAD

**Issue by artmunro** [trailsjs/trails#277]
Using the yo generator, it list supported servers, one of which is restify.  It currently is unsupported.  Is this in the works to support?

**Comment by konstantinzolotarev** [comment]
@artmunro Unfortunately for now It's just in plans and nobody working on it.

**Comment by tjwebb** [comment]
Possibly, but there hasn't been enough demand for the core team to devote resources to building it. But contributions are welcome!

**Comment by scott-wyatt** [comment]
I'm going to close this for now, as it could be implemented in a trailpack.  Please feel free to reopen!
