### ISSUE TITLE
can you tell me the plan to support koa

### ISSUE THREAD

**Issue by jason-ivy** [trailsjs/trails#288]
can you tell me the plan to support koa?

**Comment by jaumard** [comment]
No direct plan to support koa, we rely on the community to build this trailpack as the core team doesn't have enough resources to build/maintain this one. It's not really complicated if you know koa,  you have great example on how to do it with existing trailpack for Hapi and Express

**Comment by jeffrygan** [comment]
Thanks

**Comment by scott-wyatt** [comment]
I'm going to close this for now, but I'd be in support of adding a bounty for this trailpack. Please feel free to reopen if you have some ideas on it @jason-ivy.
