### ISSUE TITLE
Graphql 

### ISSUE THREAD

**Issue by jamrizzi** [trailsjs/trails#295]
Is there an official graphql implementation? If not, are there plans for one, and what would be the current advised way to implement graphql?

**Comment by Nishchit14** [comment]
It will be implemented in V3 as a default support.

@jaumard  @tjwebb will have a better answer :)

**Comment by jamrizzi** [comment]
Would love to know how you guys are planning on implementing this. If you need help let me know.

**Comment by scott-wyatt** [comment]
@jamrizzi there is a v3 branch where we are working on code coverage for this feature, feel free to dig in!  I'm going to close this until after the v3 launch. Feel free to reopen!
