### ISSUE TITLE
Custom eslint style and generator

### ISSUE THREAD

**Issue by jamrizzi** [trailsjs/trails#297]
I understand the importance of a standardized style guide, however, many user's and companies already have their own style guide that differs strongly from your style guide. What is the best way to override this?

Currently, I forked the [trails/eslint-config-style](https://github.com/trails/eslint-config-trails) to [jamrizzi/eslint-config-trails](https://github.com/jamrizzi/eslint-config-trails). This works just fine, but I'm wondering if there is a better way to handle this. Also, the generator does not work with my custom style guide. Is there a way to override the generator, or would I need to fork the generator and customize it myself?

**Comment by jaumard** [comment]
You can just change the eslint extends in the package.json and use yours (or another one). For the generator no way to override it and even if you override the generator you'll not be able to change template files because they are embedded into trailpacks directly.

**Comment by jamrizzi** [comment]
Ok, thanks
