### ISSUE TITLE
Description encoding error while generating a new file with yo trails: 

### ISSUE THREAD

**Issue by Clement-Ruiz** [trailsjs/trails#299]
#### Issue Description
When creating a model or a controller (f.e. ```$~ yo trails:model User```) and writing a quote ```'``` in the description, generated file shows a @description section with quotes replaced by ```&#39;```

#### Environment
- node version: 6.11.1
- trails version: 2.0.0
- operating system: Linux Mint 18 MATE 64-bit

**Comment by scott-wyatt** [comment]
Moving to [here](https://github.com/trailsjs/generator-trails/issues/76)
