### ISSUE TITLE
Address npm dependency issues found in master branch [Opened by bitHound]

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#30]
<p>bitHound discovered:</p> <ul> <li>1 unused package.</li> <li>1 npm package is requiring the latest version.</li> <li>1 outdated package.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/trailsjs/trails/master/dependencies/npm">bitHound</a>.</p>

**Comment by troy0820** [comment]
The unused package they are talking about is trailpack.  I know we use trailpack and latest in the package.json should be **"*"** to not be flagged as outdated.

Changing it along with a npm update --save should resolve this problem.  I can make the PR.

**Comment by tjwebb** [comment]
>  I can make the PR.

:+1:

**Comment by troy0820** [comment]
I closed this pull request because why it breaks is the *eslint module* is missing. That isn't a dependency issue and I can open up another issue for that.
