### ISSUE TITLE
Trails not loading trailpack files from config directory

### ISSUE THREAD

**Issue by christiangelone** [trailsjs/trails#301]
#### Issue Description
Hi, i am having some issues with some trailspack that need some file to exists in the config directory
for instance trailpack-realtime which needs realtime.js and trailpack-realtime whiche needs bootstrap.js there. The thing is that trails is not loading those files in this.app.config
Any help?

#### Environment
- node version: v6.11.0
- trails version: latest
- operating system: OSX

**Comment by jaumard** [comment]
Did you check that the files are also in config/index.js ? If not they are not loaded

**Comment by christiangelone** [comment]
Thanks, that was the problem ^^
and sorry for such stupidity

**Comment by jaumard** [comment]
No problem glad it works :)
