### ISSUE TITLE
Trailsjs vs Trails.js vs TrailsJS vs Trails

### ISSUE THREAD

**Issue by jamrizzi** [trailsjs/trails#303]
What is the official name of trailsjs? I've seen it written many ways. It would be nice if there was an official way to write it.

https://stackoverflow.com/questions/5621812/why-is-node-js-named-node-js

**Comment by jaumard** [comment]
Can't answer officially but for me it's Trails :) like it's Node. But it's my opinion and daily usage

**Comment by scott-wyatt** [comment]
Context is kind of key here. Using the ambiguous name of "Trails" is difficult to rank on search engines. "Trails.js" implies that it's a file, and "trailsjs" looks like a typo. Also, personally I use trails with typescript, so I tend to steer away from the ".js". I would assume most people build their apps with trails as the core framework, making it a "Trails App", but with trails being so flexible, I've seen more and more people who use it as a microservice. Personally, I call it "Trails". I think it's the most consice name, and as long as people are searching for it in the correct context, I haven't had a problem finding what I need on google/whatever.

**Comment by jamrizzi** [comment]
So the name is officially Trails, but you use Trails.js occasionally for SEO purposes? Btw, I use Trails for micro services all the time :+1:

**Comment by scott-wyatt** [comment]
Closing this issue. Not because it's resolved but because it warrants more discussion on [gitter](https://gitter.im/trailsjs/trails).
