### ISSUE TITLE
Resolve Not created

### ISSUE THREAD

**Issue by danielsalles** [trailsjs/trails#304]
#### Issue Description
In the documentation the example shows the creation of resolves automatically after the template is created. But you are not creating here in my application. Do you have a reason?

#### Environment
- node version: 8.1.4
- trails version: 2
- operating system: Arch Linux

**Comment by jaumard** [comment]
Trails is currently in V2, resolvers are in V3 (like the documentation) witch is not out yet the the generator only generate project for stable version. Most of the documentation works for V2 and V3 but resolvers no, they don't exist in v2

**Comment by danielsalles** [comment]
@jaumard How would I change a value before saving in the bank for example? Via controller same?

**Comment by jaumard** [comment]
Currently on V2 you can use the trailpack-footprint that create REST API for your models automatically, or use directly a trailpack with your chosen orm (sequelize, waterline, mongoldb...) and access it directly from your controllers/services with this.orm.MyModel....

**Comment by danielsalles** [comment]
Got it.
Can I use policy, auth and etc with footprint?

**Comment by scott-wyatt** [comment]
@danielsalles you sure can! That's how it's done in parts of trailpack-acl.  I'm going to close this issue for the time being. Feel free to reopen after we release v3!
