### ISSUE TITLE
Trailpack docs returns 404

### ISSUE THREAD

**Issue by Math3v** [trailsjs/trails#305]
#### Issue Description
Hello everyone,

I was just going through the documentation and noticed that [Trailpack](https://trailsjs.io/doc/en/extend/trailpack.md) docs returns a 404 Error.

Cheers!
Matej

**Comment by scott-wyatt** [comment]
Thanks @Math3v! We are working to make this better, we have some intermittent issues with docs between v3 and v2, and hope that we can get this resolved soon. I'll close this for now, as this is likely the issue, if after the v3 release and this is still an issue, feel free to open it back up.
