### ISSUE TITLE
V3 api problems 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#311]
#### Issue Description
Previously we were using 
`const Controller = require('trails/controller')`
Now we're supposed to remove this because Trails is exposing them in global scope. 

Problem is under a Trails project we can't remove this line, but we need to change it to:
`const Controller = require('trails/lib/controller')`

Problem is that the assignGlobal method who put api classes under global is called after the api files are loaded so it crash because classes doesn't exist yet

#### Environment
- node version: 8.9.1
- trails version: 3.0.3
- operating system: doesn't matter

**Comment by rayhaanq** [comment]
I guess this is the same for policies too?

**Comment by jaumard** [comment]
Yes it API so policies, services, controllers and models are impacted, and if you are under case sensitive system the correct line is `require('trails/lib/Controller')` it's capitalized
