### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by weyert** [trailsjs/trails#315]
I am wondering if this project is still being maintained? 

A lot of issues are open but not being acted on. I noticed that V3 is out but there is no details how you can upgrade to this version if you are using V2. Currently in my V2 project I am experiencing issues that overriding config files based on `NODE_ENV` is not working. If I try to limit the `packs` e.g. disable sequelize as not needed then it's not working for me.

**Comment by scott-wyatt** [comment]
Yes, still maintained.  Migration instructions will be published when they are ready and bug fixes for v2 will be published until they end of it's lifecycle. 
There are a ton of reasons why you might be experiencing an issue with your config, but there isn't much to go one here.  I would first check the index file of each directory in your config to make sure that your config is being exported.
