### ISSUE TITLE
V3 trailpack config override app config

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#316]
Big problem on how Trails v3 is merge config, now config put under trailpacks are overriding the config app, so whatever the user put, it will not be into account.

App config is created here https://github.com/trailsjs/trails/blob/master/index.js#L69
But after that we merge config trailpack here https://github.com/trailsjs/trails/blob/master/index.js#L94

So this mean for me that we create the config object with app config and after override values by the one on the trailpacks, witch is wrong because we want the opposite :(  
The now we don't really merge config anymore, we just replace it (see here https://github.com/trailsjs/trails/blob/master/lib/Configuration.js#L47) meaning that Arrays on mutilple trailpack (policies, footprints...) are loose and only the last one it kept :( same for objects I guess

Maybe I didn't understand how it works so let me know :)

**Comment by jaumard** [comment]
@tjwebb I would like to try to fix this, can you help me show me the way ? Did I understand it correctly first ?

**Comment by matteozambon89** [comment]
@jaumard I noticed the same when I was working on `trailpack-koa`, it's affecting all those trailpacks which has `/config` folder with public configs and not just private configs (I supposed this was the reason of this `/config` folder)

My way might be a bit unorthodox  but what I essentially did to my trailpack is:
1. on `/config` folder I left just a `trailpack.js` without any public config (e.g. I've removed `web.js`, `main.js` and `socket.js`)
2. on `/lib/schema` I wrote better `JOI` schemas which sets defaults on validation
3. on `index.js`, where `configure` method is defined, I wrote the following:
```
  configure() {
    return Promise.all([
      // update App config
      () => {
        this.app.config.set('web.server', 'koa')

        return Promise.resolve()
      },
      // Utilize JOI validator to set the formatted config
      lib.Validator.validateConfigMain(this.app),
      // Utilize JOI validator to set the formatted config
      lib.Validator.validateConfigWeb(this.app),
      // Utilize JOI validator to set the formatted config
      lib.Validator.validateConfigSocket(this.app)
    ])
      .then((result) => {
        // Update app.config.main
        this.app.config.set('main', result[1])
        // Update app.config.web
        this.app.config.set('web', result[2])
        // Update app.config.socket
        this.app.config.set('socket', result[3])
      })
  }
```

This solution is a bit more articulated but solves the issue of having trailpack config overriding the app config.

We should either have this solution as a standard trailpack (being trailpack `/config` used just for private configs) or fix that by merging trilpack config into app config.

I'll try to read Trails.Js code and let you know if I find something.

**Comment by matteozambon89** [comment]
Just noticed you guys are already working on a pull request #317

**Comment by jaumard** [comment]
Yes don't hesitate to test it and give feedbacks @matteozambon89 :) this issue must be solved on trails not on trailpacks because it's a regression from v2

**Comment by Nishchit14** [comment]
@jaumard @scott-wyatt 
In some of my application SSL is only required in `production` & `staging` env only but not in `development`

For that, I'm putting this into following `config/env` files

`config/env/staging.js`
`config/env/production.js`
```
   web: {
	ssl: {
		key: fs.readFileSync('/root/ssl/privkey.pem'),
		cert: fs.readFileSync('/root/ssl/fullchain.pem')
	},
	portHttp: 3000,
	port:8443,
	redirectToHttps: true
   }
```

**PROBLEM**

Now when we start the server in `development` then it throws an error like `fullchain.pem` & `privkey.pem` file path not found. 
Because the SSL files exist on production/staging server, not on local.

**EXPECTED**
If we're running the server in `development` environment then it should ignore the config value given in other environment files.
