### ISSUE TITLE
npm ERR! notarget No matching version found for trailpack-express@^3

### ISSUE THREAD

**Issue by hansiemithun** [trailsjs/trails#318]
#### Issue Description
Error while installing trails for the first time

#### Environment
- node version: 8.9.4
- trails version:  Latest
- operating system: Windows

**Comment by scott-wyatt** [comment]
Trailpack-express 3 is still working on being released. Sorry about that.

**Comment by Aayrton** [comment]
Hey !
I have the same issue when i try to install trails with Yeoman.
Seems like Yeoman try the install the wrong version of trailpack-express.

Any workaround to force YO to install the v2 ?

**Comment by jaumard** [comment]
trailpack-express v3 has been released so should be ok now, also if you want the generator to generate a v2 you need to install v2 version of the generator, not the v3
