### ISSUE TITLE
this.app.packs is not defined

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#32]
this.app.packs is not copy correctly from this.app.config.main.packs cause it's undefined.
One fix can be to modify https://github.com/trailsjs/trails/blob/master/index.js#L77 and add `this.packs = packs`

First issue report for the record :
https://github.com/trailsjs/trailpack-hapi/issues/5

**Comment by konstantinzolotarev** [comment]
I think this issue is related.

After generating new app using `yo` and `npm start` getting this error: 

```
****/OpenSource/trails/test/node_modules/trails/index.js:89
    const instantiatedPacks = this.config.main.packs.map(Pack => new Pack(this))
```
