### ISSUE TITLE
would like to hear back from you guys before i start forking all trails related repositories

### ISSUE THREAD

**Issue by Mishel-M-IT** [trailsjs/trails#327]
#### Issue Description
Hello there. sorry for creating this pull request. for a while i was following you guys and i liked the idea behind trails js. But there is a fact that i have some ideas about implementation and have things i wanna add to trails frameworks and generators. I think this repository and other trailsjs related repositories are being inactive. so before forking whole project and starting to go my own way with it wanted to know whats up with you guys? you have any plans in mind which i can possibly help with? to avoid overlapping works

#### Environment
- node version: ???
- trails version: ???
- operating system: ???

**Comment by scott-wyatt** [comment]
Hi @Mishel-M-IT, I was in a bit of the same boat, so I started [Fabrix](https://github.com/fabrix-app) which will be very active. Trails is not abandoned, just that many of the core maintainers are very busy and Fabrix is looking for active contributors.

**Comment by Mishel-M-IT** [comment]
@scott-wyatt thanks scott. i will take a look at it. im already in a project and will see if im gonna remain in team as senior developer or not in few days. after that ill manage my time and check everything.
thanks again.
