### ISSUE TITLE
HATEOAS

### ISSUE THREAD

**Issue by yannbertrand** [trailsjs/trails#35]
One thing that was not implemented in Sails was the HATEOAS principle.

Basically, when doing a request, the response must contain informations on how to access to others states of the resource (removal, edition, etc...) or a linked one.

You can find more informations about this concept on [Wikipedia](https://en.wikipedia.org/wiki/HATEOAS) and on the O'Reily book [
RESTful Java with JAX-RS](https://www.safaribooksonline.com/library/view/restful-java-with/9780596809300/ch01s02.html).

I think you don't want to have overcomplicated API responses but this is a part of the REST architecture that I find missing in Sails.

**Comment by YannBertrand** [comment]
After a discussion about this with @jaumard, it's true that it would be hard to add some of these informations directly into the footprints as it's business-related.

However it would be nice to have a method in the `response` object which we could use in custom footprints or custom actions.

E.g in a `findOne()`:

    Resource
      .findOne(1)
      .exec((err, resource) => {
        // Handle error
        // ...

        res.hateoas.add('list', 'GET', '/resource') // Could even be improved using a service Hateoas.list(Resource)
        res.hateoas.add('update', 'PUT', '/resource/' + resource.id) // Hateoas.update(Resource, id)
        res.hateoas.add('delete', 'DELETE', '/resource/' + resource.id) // Hateoas.delete(Resource, id)

        res.ok(resource)
    })

which would return something like

    200 OK
    {
      meta: {
        list: {
          method: 'GET',
          url: '/resource'
        },
        update: {
          method: 'PUT',
          url: '/resource/1'
        },
        delete: {
          method: 'DELETE',
          url: '/resource/1'
        },
      }
      content: {
        ...
      }
    }

**Comment by JemiloII** [comment]
I don't know if I'd use this, however, if I did, I think I'd like something simple to view, since we are doing rest.
 `MyResouceHATEOAS.js`

```
{
    list: {
        get: '/resource'
    },
    update: {
        put: '/resource/:id'
    },
    delete: {
        delete: '/resource/:id'
    }
}
```
or even:

```
{
    list: ['get', '/resource'],
    update: [put, '/resource/:id'],
    delete: ['delete': '/resource/:id']
}
```

Then in the code:
`Hateoas('list', 'update', 'delete');` or `Hateoas(['list', 'update', 'delete']);`

It's an idea, unless you think it'll be hard for others to understand, maybe it looks magical

**Comment by YannBertrand** [comment]
> I think I'd like something simple to view, since we are doing rest.

I can understand your point of view, but the REST standard is not about simplifing the views (as far as I know :wink:).

Of course it would be great to make this optional as you said, but I'm pretty sure it will be needed pretty quickly (basically whenever you need to retrieve all your data (see #34)). We can embrace that pagination problem with HATEOAS.

For example:

*GET /resource?page=2*

    200 OK
    {
      meta: {
        total: 55,
        nbOfPages: 6,
        page: 2,
        nbOfElements: 10,
        previousPage: 1,
        nextPage: 3,
        firstPage: 1,
        lastPage: 6
      },
      content: [
        {
          meta: {
            get: ['GET', '/resource/10'],
            update: ['PUT', '/resource/10'],
            delete: ['DELETE', '/resource/10']
          }
          id: 10
      ],
      ...
    }

I hope you can understand me better now :smile:.

**Comment by jamesjwarren** [comment]
Would be useful but definitly should be an add-on rather than 'baked-in'. Already a great node module for hal document formatting here: https://www.npmjs.com/package/hal

**Comment by scott-wyatt** [comment]
Hi everyone, this issue is a bit stale and we are prepping the release of v3, I'm going to close this for  now, please feel free to continue the debate!
