### ISSUE TITLE
Use named routes

### ISSUE THREAD

**Issue by ArsalanDotMe** [trailsjs/trails#37]
One of the things that we very often end up needing is to generate a url for some route in our app. 

For example, let's say I have a route like this:
`GET /resource/:resourceId/action/param1/:param1/param2/:param2`

Later in our app, we need to generate an anchor tag with the link to that url. With the current implementation, routing logic will have to be duplicated into the function that creates the full urls.

One solution for this problem is using something like [named-routes](https://www.npmjs.com/package/named-routes). ASP.NET MVC5 has its own way of reversible route definitions that might be useful to study.

**Comment by maissani** [comment]
Nice feature , 

It would be nice that named route behave like it :
## Abstract Route Concept :
 
Abstract Route 
 ```
  {
    name: "default"
    abstract: true
    path: '/api/v1/default'
  }
```
A route that use the previous abstract route: 
```
  {
    name: 'default.info'
    method: [ 'GET' ],
    path: '/info',
    handler: 'DefaultController.info'
  }
```
Resolved route will be : /api/v1/default/info
  
But only enabled if in footprints.js 
  ```
  module.exports = {
    /**
     * Enable named abstract and named Route Resolution 
     * Omit named routes if false
     */
    abstractRoutes: true
  }
```


With that feature, enabling abstractRoutes would permit to use not named routes too.
Abstract routes would permit : abstractroute.anotherabstractroute.lastroutethatcontainshandler

The stateProvider of AngularJS use this concept to build named routes.

My opinon is that yould be nice to have the choice. 

This long message is just an idea but would be a future feature only if there is no impact for router perfs

**Comment by scippio** [comment]
It's very important feature! ... I think we can imspired in [named-routes](https://www.npmjs.com/package/named-routes) module.

But I don't know where is the right place for connecting to server/controller/view etc...  We can add field to route def:
In trailpack-router/lib/schemas/route.js:
```
+0200
@@ -1,6 +1,7 @@
 const joi = require('joi')
 
 module.exports = joi.object().keys({
+  name: joi.string(),
   method: joi.alternatives().try(
     joi.string(),
     joi.array()
```

It's specific for server type so next step will be for example in the trailpack-express4 ... ?

**Comment by jaumard** [comment]
Hapi already allow you to give name to your routes with `id` field  (@scippio `name` field is not allowed by Hapi), Express allow any field under his route configuration so it can also use `id`. 
So I think it's possible to implement without to much modifications... 
Only thing that can be tricky is this (from hapi's doc) : 

> _id_ - an optional unique identifier used to look up the route using server.lookup(). **Cannot be assigned to routes with an array of methods.**

**Comment by scott-wyatt** [comment]
I think at this point this would be more appropriate for trailpack-router if it is still outstanding.  Closing for now, please feel free to reopen!
