### ISSUE TITLE
possible new feature? angular 2 for frontend?

### ISSUE THREAD

**Issue by davidxiao** [trailsjs/trails#40]

**Comment by dharness** [comment]
I think if this introduced it would be related to #64 - specifically because Angular 2 uses TypeScript heavily

**Comment by tjwebb** [comment]
@jaumard @scott-wyatt this is basically addressed by https://github.com/calistyle/trailpack-treefrog, right?

**Comment by jaumard** [comment]
Yes mainly :) just this need to be fixed officially https://github.com/trailsjs/trails/issues/242

**Comment by scott-wyatt** [comment]
We have an example app that has angular2, angular-universal, typescript, and trails all working together in node 6+ [here](https://github.com/CaliStyle/treefrog-universal) @davidxiao 

As far as generating trails apps in languages other than just JS such as TypeScript, that's what Treefrog will do, but it's not quite finished.

**Comment by scott-wyatt** [comment]
I'm going to close this for now.  As I think frontend's are better built as trailpacks or on the consumer end.  Please feel free to reopen if need be!
