### ISSUE TITLE
Class for models, controllers, policies and services

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#42]
It would be nice to have some classes : 
`TrailsModel`, `TrailsController`, `TrailsPolicy` and `TrailsService` instead of `{}` directly. It can be useful to extends some trailpack functionalities from trails project. 
It can be more 'cleaner' / easy to understand/learn to have classes for this kind of objects.

**Comment by listepo** [comment]
:+1:  I think it is right

**Comment by jaumard** [comment]
Maybe this classes can be put under https://github.com/trailsjs/trailpack, like this trails and trailpacks api can implements them. 
We can change `index.js` to have somethings like : 
```
module.export = {
     Trailpack = class Trailpack {...},
     TrailsModel = class TrailsModel {...},
     TrailsController = class TrailsController {...},
     TrailsPolicy = class TrailsPolicy {...},
     TrailsService = class TrailsService {...}
}
```
And then to create a trailpack : 
```
const Trailpack = require('trailpack').Trailpack
module.exports = class MyTrailpack extends Trailpack {...}
```
Instead of (currently) : 
```
const Trailpack = require('trailpack')
module.exports = class MyTrailpack extends Trailpack {...}
```
What do you think @trailsjs/maintainers ?

**Comment by JemiloII** [comment]
could we shorted the export object properties?

module.export = {
     Trailpack = class Trailpack {...},
     Model = class TrailsModel {...},
     Controller = class TrailsController {...},
     Policy = class TrailsPolicy {...},
     Service = class TrailsService {...}
}

**Comment by listepo** [comment]
@JemiloII 

```javascript
class TrailsModel {
  constructor() {
    this.attributes = {
      'name': 'string',
      'age': 'integer'
    }
  }
}
```
or
```javascript
class TrailsModel {
  get attributes() {
    return {
      'name': 'string',
      'age': 'integer'
    }
  }
}
```

**Comment by tjwebb** [comment]
> Maybe this classes can be put under https://github.com/trailsjs/trailpack, like this trails and trailpacks api can implements them. 

This had occurred to me when I wrote the original implementation back in November, but I decided to stick with plain object definitions for some assets. Reasons are below:

### Controllers, Services, Policies
I have no reason here. I think having a `TrailsController` or `TrailsService` class to extend from would be nice, and help prop up trails applications with a bit of additional, helpful structure.

### Models
I think here a `TrailsModel` class makes less sense for a couple reasons.
1. Each ORM will implement their model definitions differently. Encouraging inheritance from a class might make this more awkward.
2. Most of the model's properties are static, and es6 classes don't support static properties at all. Everything would have to be instance properties, which would make the code for defining a model overly complicated and messy.

**Comment by jaumard** [comment]
Ho didn't know Models working like this. Make sens to keep an object then. 

But for controller/policiy/service it will be really nice to have classes. Now with ES6 javascript have a really inheritance system it will be a shame to not use it. We finally can make `super.myParentMethod()` ^^. In sails for example it make me sick to merge controllers/services to extend them cause we loose parent methods (or use some very ugly things to keep it :/).
Maybe instead of binding the methods you can bind object create with classes ? 
Don't know how to bind them but if you do something like : 
```
TrailsApp.controllers.MyController = require('api/controlllers/MyController')
``` 
can become : 
```
TrailsApp.controllers.MyController = new require('api/controlllers/MyController')()
```
Can it work ?

**Comment by ghaiklor** [comment]
For me, I don't see any issues with `Model` base class. We can make accessors which must return POJO for adapter that used in this model. Don't need to handle this ourselves. Like this:

```js
export class User extends Model {
  get schema() {
    return {
      // here is our model definition for mongoose, waterline, whatever
    }
  }

  onTransform() {
    // transformation
  }
  
  onSerialize() {
    // serialization
  }

  // and so on...
}
```

**Comment by tjwebb** [comment]
> export class User extends Model {
  get schema() {
    return {
      // here is our model definition for mongoose, waterline, whatever
    }
  }

This seems like unnecessary ceremony. I don't want to use classes just because it'd be nice to use them. What are some concrete benefits of this approach?

**Comment by jaumard** [comment]
I like the approach @ghaiklor 

@tjwebb Same as controllers/services/policies to have the possibility to declare some stuff on mother class and don't have to duplicate them (or create unnecessary utils file) in daughter classes. And by stuff I mean functions / validations / attributs. This also "force" orm trailpack to have the same interface and don't have totally different model between different ORM

**Comment by listepo** [comment]
@ghaiklor +1

**Comment by JemiloII** [comment]
I like the idea of having a base Model structure. Especially if its pojo format. This way, we can have create one orm adaptor to deal with the model. One of the huge reasons I would like it to be this way, is that I do intend on baking out some of the trails express work. It would be nice to use the same model file formats and adapters that trails hapi, koa, or whatever the next new thing is uses.

Btw, who else is working with trails and express 4 currently? As another note, im just exclusive to express, i love hapi and express the same. I just hope that once trails get going with a stable release, I can have my team at or or other sails/express projects I have can just easily be dropped into trails as is. The old express code works as you expected along side the new code. This way, integration can go smoothly. :)

**Comment by jaumard** [comment]
I think if you decide to do this, it have to be done for the beta version because after too much Trailpack will existe and it will be more difficult to implement this.

**Comment by tjwebb** [comment]
I just started working on this, and then stopped. There are more issues with inheritance besides the ones I mentioned above. I think we need to schedule this for a future release. 

1. es6 methods are not enumerable, so the handy `_.functions` does not work. We need to iterate manually and use `Object.getOwnPropertyNames()`. 

2. `Object.getOwnPropertyNames()` only looks at the current object, and ignores the prototype chain. So we'd also need to recursively iterate up the prototype chain and aggregate all the method names.

3. The `this` context. Trails intentionally does not expose any global variables. Instead it binds the application to the context of the controllers, policies, and services so that application resources are available on the `this` object. A class defines its own `this` context, so we'd need to merge the two contexts together when the method is bound.

**Comment by jaumard** [comment]
I understand, if I can help with this let me know :)

For 1 and 2 : 
```
function getAllPropertyNames( obj ) {
    let props = []
	let objectRoot = new Object()
	while ( !obj.isPrototypeOf(objectRoot) ){
		Object.getOwnPropertyNames( obj ).forEach(function ( prop ) {
            if ( props.indexOf( prop ) === -1 && prop != 'constructor') {
                props.push( prop )
            }
        });
        obj = Object.getPrototypeOf( obj )
    }
    return props
}
```
Maybe for the 3 we can just pass the app on constructor : 

```
constructor(app) {
    this.app = app // or this.api = app.api
  }
```

**Comment by tjwebb** [comment]
> Maybe for the 3 we can just pass the app on constructor :

This is reasonable, we'd just need to change all the controllers currently written (luckily, not too many!)

**Comment by tjwebb** [comment]
Alright, I took the plunge and I'm re-doing controllers, services, policies, and models to be classes and inherit from standard es6 classes to provide structure.

see:
- https://github.com/trailsjs/trails-model
- https://github.com/trailsjs/trails-controller
- https://github.com/trailsjs/trails-service
- https://github.com/trailsjs/trails-policy

Hopefully I can get this done tonight and tomorrow. I'm giving 3 talks next week on Trails!

**Comment by jaumard** [comment]
Classes are now used so I close this.
