### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#45]
Trails should support i18n from the beginning, and as such should be included in the core. It will likely be the only dependency included in the core, possibly ever.

**Comment by tjwebb** [comment]
An initial implementation is here: https://github.com/trailsjs/trailpack-core/commit/7b2fa5a1ba151098ab3cdfa58fdfdd517bfb4343

**Comment by kokujin** [comment]
i18n-node ( https://github.com/mashpie/i18n-node) and a few others are quite nice, why should i18n be in the core?

**Comment by tjwebb** [comment]
i18n-node hasn't been published to Github in a year and a half, and I emailed the maintainer about this with no response. I decided to use i18next, which has similar adoption as i18n-node but is updated regularly. It'll be included in trailpack-core.

**Comment by tjwebb** [comment]
Implemented 1.0 with i18next
