### ISSUE TITLE
Provide catchAll route in ViewController for Hapi

### ISSUE THREAD

**Issue by troy0820** [trailsjs/trails#5]
Hapi has a catchall route to handle 404 requests.

**Comment by tjwebb** [comment]
I think for all the web services packs (hapi, express, koa, *et al*) we should setup default pages for 404, and 5XX errors. 

Currently Sails has some adorable barrel floating in the ocean graphic that shows up. Along the lines of the twitter failwhale: https://upload.wikimedia.org/wikipedia/en/d/de/Failwhale.png

**Comment by troy0820** [comment]
Okay, so each trailpack will have to configure this capability with each view engine it's capable of.

**Comment by tjwebb** [comment]
Yea, but I think the 404/500 views themselves can probably be stored centrally in this repo since they'll just be HTML.
