### ISSUE TITLE
coffeescript?

### ISSUE THREAD

**Issue by alexiskattan** [trailsjs/trails#64]
Any plan to support coffeescript at the application level?

**Comment by dharness** [comment]
Is there a reason to support Coffeescript in particular, as opposed to say, TypeScript?

**Comment by jaumard** [comment]
I didn't know TypeScript or Coffeescript but they or both compiled into Javascript right ? Trails support webpack so all you need to do is a webpack configuration who compile this file at start. So Trails is already kind of compatible or am I wrong ?

**Comment by tjwebb** [comment]
@jaumard yea, I think this is something that should be supported in the project's build process.
