### ISSUE TITLE
Website mentioned in the repo description doesn't work

### ISSUE THREAD

**Issue by hussainanjar** [trailsjs/trails#66]
See attached
<img width="607" alt="screen shot 2016-01-06 at 12 16 08 pm" src="https://cloud.githubusercontent.com/assets/459445/12137108/723c7580-b46f-11e5-9306-baccf7120047.png">

**Comment by metzuda** [comment]
See #22

**Comment by konstantinzolotarev** [comment]
@hussainanjar Thank you! Please follow discussion in existing issue.
