### ISSUE TITLE
create docker image for trails application

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/trails#75]
and share on dockerhub: https://hub.docker.com/u/trailsjs/

**Comment by nrempel** [comment]
Is this a docker image containing the example trails app or is it a starting point for a docker image?  What's the use case here?

**Comment by tjwebb** [comment]
There could be many. Initially, probably to serve as a development environment. Eventually, we'd evolve that into a container suitable for deployment.

**Comment by jaumard** [comment]
I just try to create an image with the default generated project here with hapi and express4 : 
https://hub.docker.com/r/jaumard/trails-express4/
https://hub.docker.com/r/jaumard/trails-hapi/

That's what you mean @tjwebb ?

**Comment by jaumard** [comment]
Also you create the user Trailsjs but you also can create an organisation on hub docker

**Comment by scott-wyatt** [comment]
@tjwebb close discussion? (so we can close the milestone)

**Comment by scott-wyatt** [comment]
There are now docs for creating Docker images easily with trails https://github.com/trailsjs/doc/issues/42, however they are not on the website yet as they are pending release for v3.  Closing this for now. Reopen if you please!
