### ISSUE TITLE
Config/web.js should be move under trailpack

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#76]
I think the `config/web.js` shouldn't be under `trails/archetype` and be under `trailpack-hapi/archetype`, `trailpack-express4/archetype`... If some web server have default values other than `port` to put in it they can't actually.

**Comment by jaumard** [comment]
Also `config/weppack.js` should move on `trailpack-webpack`

**Comment by jaumard** [comment]
Done for web.js here 
https://github.com/trailsjs/trails/pull/131 and https://github.com/trailsjs/trailpack-hapi/pull/65

**Comment by konstantinzolotarev** [comment]
@tjwebb @jaumard Super. I'd like to merge it ASAP. because want to add adiitional property into hapi `config/web.js` file.

**Comment by jaumard** [comment]
Closing this because PRs was merged.
