### ISSUE TITLE
Where public dir can be configured

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#77]
Sails by default use `.tmp/public` some others prefer `www` or `www/public`... maybe it can be nice to have somewhere to configure this. Maybe in `web.js` ? Webpack, Gulp and other tasks runner can retrieve this value and build assets.

**Comment by tjwebb** [comment]
Yes, we should do this under `config.main.paths`.

**Comment by jaumard** [comment]
Closing this, paths must be configure into `config.main.paths`
