### ISSUE TITLE
Task: describe the anatomy of trails

### ISSUE THREAD

**Issue by nrempel** [trailsjs/trails#78]
I'm hoping to dig in more and knock off some tasks soon once I find some time outside of work.

One barrier for me is understanding the anatomy of trails and how trailpacks interact with the system.

For example, what is the purpose of the archetype directory? lib? etc.

Maybe this is a good piece for the github wiki, or is there going to be a separate RTD site?

**Comment by randallmeeker** [comment]
I know I suggested back in the day on sails, that it would be great to have a developer google hangout where interested collaborators could get a walk through / tour from core devs. This could also help us to help them write the necessary documentation.

**Comment by jaumard** [comment]
I wrote a tutorial for trailpack (not working yet cause not all modules are on npm but it can help to understand) http://blog.jaumard.com/en/2016/01/06/create-a-trailpack-for-trails/ `archetype` are not part of this tutorial cause `archetype` are only use by yo generators for now. `archetype` is only template files that will be copy on trails project. Yo generator take the files and create your project with them. 

Later all trailpack will be able to have there own `archetype` folder to share default config files for example

But yeah doc will come :)

**Comment by nrempel** [comment]
+1 for that

**Comment by kokujin** [comment]
+!

**Comment by maissani** [comment]
I am working on Anatomy & Concept & creating some videos about use cases. 
There is a lot of work to be done, but i am pretty sure that i will try everything possible to break all the devel's barrier.
