### ISSUE TITLE
No A Record for WWW host on domain

### ISSUE THREAD

**Issue by e0steven** [trailsjs/trails#82]
There is no A record for www.trailsjs.io, it dumps you to a 'park' page.

**Comment by tjwebb** [comment]
Ah yes, you mentioned this last night. Thanks for filing this, I would indeed have forgotten.

**Comment by Alaneor** [comment]
It still shows a generic registrar page. And the naked domain redirects to this github repo, not sure if that's desired behaviour or not.

**Comment by tjwebb** [comment]
Resolved.
