### ISSUE TITLE
 Failed at the test-3@0.0.0 start script 

### ISSUE THREAD

**Issue by RaedsLab** [trailsjs/trails#86]
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! test-3@0.0.0 start: `node server.js`
npm ERR! Exit status 1

npm ERR! Failed at the test-3@0.0.0 start script 'node server.js'.

**Comment by tjwebb** [comment]
Is this after generating a new trails app?

**Comment by RaedsLab** [comment]
vanilla generation goes fine, then this occurs when I start

**Comment by jaumard** [comment]
Do you always have this with the last version ?

**Comment by Alaneor** [comment]
This does not look like a complete output. Is there nothing more on the screen?
And what happens when you run the project without `npm run start` and doing directly `nodejs server`?

**Comment by tjwebb** [comment]
@RaedsLab closing until more information is provided.
