### ISSUE TITLE
Footprint conflict

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trails#90]
I have `controllers: true` under `config/footprint.js` so Trails map all controllers methods. But if I want to add a route like this : 
```
{
    method: ['POST', 'PUT'],
    path: '/default/info',
    handler: 'DefaultController.echo'
}
```

I have this error : 
`Trace: [Error: Route id [footprint] /default/info -> DefaultController.info for path /default/info conflicts with existing path /default/info]`

Expected behavior : post / put have to be overridden.

**Comment by tjwebb** [comment]
I've resolved this in the latest version of trailpack-hapi. I removed the `id` field from the route object, which fixes this issue.

It occurs because hapi does not allow `id` to be set for routes which support multiple http methods.

**Comment by jaumard** [comment]
Fix on last version
