### ISSUE TITLE
Feature request: Web server configuration and transparency

### ISSUE THREAD

**Issue by kokujin** [trailsjs/trails#93]
**It would be nice to have a configuration file for the selected web server. Something along the lines of "config/server.js".**

Reasons? 
* One could be porting custom middle-ware and their configurations from existing Express 4 of Hapi applications.
* One might decide to switch out a server in mid development, at the moment everything is just abstracted away somewhere in Trails internals.

I apologize if I am mistaken and this option already exists.

**Comment by jaumard** [comment]
The file `config/web.js` is for the web server next it will be moved into each web server trailpack (https://github.com/trailsjs/trails/issues/76) like this each web server trailpack can add it's own configuration.

**Comment by jaumard** [comment]
Now `web.js` is included in each web server trailpack 
https://github.com/trailsjs/trailpack-express4/blob/master/archetype/config/web.js 
and 
https://github.com/trailsjs/trailpack-hapi/blob/master/archetype/config/web.js

**Comment by jaumard** [comment]
@tjwebb @wbprice I think this is done now :) can be close
